### ISSUE TITLE
Increase the number of address matches to 10?

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1]
For discussion.   While doing support calls, one hang up is that the address someone is looking for somehow is NOT in the top 5 results quick enough for a typical user.. While this is an exception rather than the rule, is it possible to display the top 10 matches while searching instead of 5?  
<img width="335" alt="image" src="https://user-images.githubusercontent.com/699333/70565603-144ec500-1b58-11ea-8871-5292ecc13341.png">

**Comment by aarontitus** [comment]
Closing for now.
