### ISSUE TITLE
Hurricane Hanna Default Bug

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1013]
**Describe the bug**
Several users have reported that Hurricane Hanna is the default incident no matter what they try. I confirmed this in `user_users.states`. One user even got a new computer and the issue recurred. I instructed them to take the following steps, and recorded their `states` at each stage, revealing some very strange behavior.

**To Reproduce**
1. User 21312 reported this problem. I reset his user.states to `{}`.
2. He got a new computer and reported the same problem. His user.states was:
`{"filters": {}, "incident": "205", "incidents": {"205": {"filters": {}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 29.03215782622282, "lng": -93.74084472656251}, "_southWest": {"lat": 24.98107885823501, "lng": -102.48596191406251}}, "showingTable": false, "appliedFilters": {}}, "206": {"filters": {}, "showingMap": true, "showingTable": false, "appliedFilters": {}}, "207": {"filters": {}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 42.01170962836147, "lng": -91.67247533798219}, "_southWest": {"lat": 41.9985072696267, "lng": -91.70663595199586}}, "showingTable": false, "appliedFilters": {}}, "208": {"filters": {}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 30.237046119826534, "lng": -93.26208114624025}, "_southWest": {"lat": 30.17562796153882, "lng": -93.39872360229494}}, "showingTable": false, "appliedFilters": {}}, "209": {"filters": {}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 41.35415128126335, "lng": -110.71333249787426}, "_southWest": {"lat": 40.49502136927284, "lng": -112.89961179474926}}, "showingTable": false, "appliedFilters": {}}, "210": {"filters": {}, "showingMap": true, "showingTable": false, "appliedFilters": {}}, "211": {"filters": {}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 37.68382032669382, "lng": -73.32275390625001}, "_southWest": {"lat": 21.98380141738471, "lng": -108.30322265625001}}, "showingTable": false, "appliedFilters": {}}}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 30.429359536352255, "lng": -87.66355991363527}, "_southWest": {"lat": 30.414038703083474, "lng": -87.69772052764894}}, "showingTable": false, "showingLegend": false, "appliedFilters": {}}`

3. I reset his user.states to `{}` again.
4. "Phone" was open, and Hurricane Sally was selected. I asked him to open a new "Work" tab. As soon as he did so, his user.states correctly updated to:
`{"incident": 210, "incidents": {}}`
Note: The map was slow to load, so no lat/lon information had saved at this point.

5. Next, I told him to change his incident to Hurricane Hanna. He did, and confirmed that the map loaded. **BUG**: However, his states indicated that the `incident_id` was `null`:
`{"incident": null, "incidents": {}}`

6. Next, I on the "Work" tab I told him to change his incident back to Hurricane Sally. The page reloaded and indicated "Sally," but **BUG** instead of reloading the "Work" page, forwarded to the dashboard. **BUG** Further, even though the incident selector said "Sally," his `states` was set to Hurricane Hanna (205):
`{"incident": 205, "incidents": {}}`

**Comment by BradenM** [comment]
Closed by 5a9ccdf5da632b61a399c4bf59d4348acde68e0a
