### ISSUE TITLE
Add browser, browser-version, os, ipv4, ipv6 to user.states

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1037]
**Describe the problem**
When we are diagnosing problems, doing technical support, and designing, we need to know the browsers our users are using on an individual basis.

**Describe the solution**
Every time user_states is updated, capture the user's `browser`, `browser-version`, `os`, `ipv4`, and `ipv6` in `user_users.states`.
The user states will be captured in `event_events_logs` for historical purposes (e.g. tracking popular browsers over time).

**Additional context and instructions**

**Comment by tabiodun** [comment]
@aarontitus This is what it will look like in the states

```
{
userAgent: {browser: {name: "Chrome", version: "85.0.4183.121"},…}
browser: {name: "Chrome", version: "85.0.4183.121"}
engine: {name: "Blink"}
os: {name: "macOS", version: "10.15.1", versionName: "Catalina"}
platform: {type: "desktop", vendor: "Apple"}
}
```

**Comment by aarontitus** [comment]
@tabiodun This looks good. 1. I don't see ipv4 and ipv6 in the list. 2. Can you tell me when we will see this reflected in production? I just took a look at my states and didn't see any of this yet.

**Comment by tabiodun** [comment]
Did we add the requirement for ip from the frontend later? I think I might have missed that. Let me see if I can get it. But from the frontend is less reliable.
