### ISSUE TITLE
Incident ID missing from form

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1051]
Bug.  when a call comes in, sometime she incident ID is not being set and therefore you only get section 1 for the form.   The quick fix is to pick another incident, then switch back to the correct incident.. it is now set properly and you get the whole form.

**Comment by BradenM** [comment]
Closed by https://github.com/CrisisCleanup/crisiscleanup-3-web/commit/1ff66fe96fd09376666521ff8ca08073072ff532
