### ISSUE TITLE
Remove the feature where we auto send a survivor to message if no agents are online.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1053]
we do this because it is better to hold for a while and get luck if an agent pops on, then falling to the back of a callback queue line.

**Comment by BradenM** [comment]
Closed by https://github.com/CrisisCleanup/crisiscleanup-3-api/commit/b373b95f74d8a87db9fb0b59e50d169bd3dfeae1
