### ISSUE TITLE
Null NULL address killer.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1060]
this video shows how we get those stupid null addresses in our system.   to re-create it, just add an address OUTSIDE the boundaries of an incident.   if you say "continue anyway" it will foobar the address.    

https://crisiscleanup.slack.com/files/U6XHW5T6H/F01CCL3D0F4/screen_recording_2020-10-10_at_6.52.35_pm.mov

- [ ] prevent an address from going all null on me when I choose to allow it even if it is out of an incidents boundaries.

**Comment by BradenM** [comment]
Related #972
