### ISSUE TITLE
evil loop because the phone service can't make a real connection.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1061]
had an evil loop happen...  we need too test how the system mis-behaves when the persons number "is not taking calls right now". its like it does not really make the full connection and therefore does bad stuff.   This is the tricky number to try out.  (850) 465-2586

**Comment by BradenM** [comment]
Boom. Goner for _good_.

**Comment by BradenM** [comment]
Closed in https://github.com/CrisisCleanup/crisiscleanup-3-api/commit/17c138c37c39a304cae906f71d91e4c66a223b88
