### ISSUE TITLE
Volunteer on phone count off

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1067]
math is often wrong on stats.  

<img width="551" alt="image" src="https://user-images.githubusercontent.com/699333/95810375-6b707980-0cd6-11eb-9ee4-01e8345776f9.png">

**Comment by BradenM** [comment]
Closed by https://github.com/CrisisCleanup/crisiscleanup-3-api/commit/e22776848fe2e5cec054cbf452bd96298a5281f1

This was related to the issue that was causing people to stop receiving outbounds (also fixed).
