### ISSUE TITLE
ConnectFirst Phone System sometimes not Updating/Creating Outbound Statuses.

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#1068]
**Describe the bug**
Seems that the Connect First phone system sometimes allows outbound calls to "slip by" without creating and or updating a status for the call.

This is leading to people redialing outbounds that have already been taken care of.

See video for more details:
https://crisiscleanup.slack.com/files/US0MGEX7X/F01CR629LQZ/screen_recording_2020-10-10_at_10.38.56_am.mov

**To Reproduce**
Unsure. Do not know how the CF system handles outbounds.

**Additional context**
This is coming from [this slack conversation](https://crisiscleanup.slack.com/archives/C79MG41GA/p1602375376095200) (with some redactions.)

> Here is what we know:
1.) **User who created the existing case** is not using ~~phone beta~~ (by beta I mean AWS system)
2.) **The Caller** called IN twice, both times she was routed to the ring flow.
3.) **The Caller** WAS received by **User who created the existing case**, via the Ring system.
4.) It gets fuzzy here, because we dont get this data from ring, but from what I can tell, it looks like **User who created the existing case** created a case then added the note.
5.) There is NO existing dnis status for the call however, meaning the outbound completion never changed. I'm not sure when Ring system updates the status, but it never happened here.
6.) When YOU took the call, you completed the outbound and she will not called again. This is the only status that is associated with her DNIS.
So there is a problem here, but its with the Ring system. Not sure at which point that updates outbound status, but it never happened.

This was determined by the following queries (see [here](https://crisiscleanup.slack.com/archives/C79MG41GA/p1602376052099900)): 
```sql
-- DNIS: ***** (**Caller** Dnis) Can see she HAS received 3 total calls.
SELECT * from phone_dnis WHERE dnis = ******;

-- Any statuses associated with Caller's DNIS (Only existing one is Ross's)
SELECT * from phone_dnis_statuses WHERE dnis_id = 148811;

-- Any events that have ****'s DNIS associated (only will show Ross's events b/c connect system)
SELECT * from event_events_log WHERE attr -> 'dnis' like '%*****' OR attr -> 'dnis1' like '%*****' ORDER BY created_at DESC

-- Can see that CALLER was routed to Ring both times and that she called in twice originally.
SELECT * from phone_outbound WHERE dnis1_id = 148811;
SELECT * from phone_inbound WHERE dnis_id = 148811;

-- Can that USER WHO CREATED EXISTING CASE has never created a DNIS status and is NOT using AWS system
SELECT * from user_users WHERE first_name like '***' and last_name like '***'
SELECT * from phone_dnis_statuses WHERE created_by = 22002
SELECT * from beta_features_users WHERE user_id = 22002

```

**Comment by aarontitus** [comment]
Old.
