### ISSUE TITLE
Generate appropriate sizes for static assets

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#1080]
**Describe the problem**
Currently we do not perform any dynamic (or pre-processing) of user uploaded static assets.

**Describe the solution**
Either:
1.) Run some preprocessing of uploaded assets and pre-generate appropriate sizes.

or

2.) Dynamically process assets to resize just-in-time by utilizing Lambda@Edge or similar.

Then, on the web-side of things, add a new component or vue directive to specify an image size that will be used to generate the appropriate src url.

This issue supersedes API#200, #1077, #642, API#111

**Comment by tabiodun** [comment]
Done
