### ISSUE TITLE
Adapt Layer Upload tool to SVI

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1095]
**Describe the problem**
We have created a new location table specifically for SVI data. It mimics the existing layer upload tool, except that it will dump data into `location_svi`, instead of `location_locations`.

Important issues:
- All meta data is also dumped into `location_svi.attr`.
- RPL_THEMES is the over-all SVI float value, that is also copied to the top level model, into `location_svi.svi_value`
- FYI, any value of `-999` means `null`. I recommend we input as `null`, rather than `-999`.

**Describe the solution**
Download the data that will need to be uploaded, from here:
https://data.cdc.gov/Health-Statistics/Social-Vulnerability-Index-2018-United-States-trac/4d8n-kk8a
https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html

**Additional context and instructions**
Dependency:
https://github.com/CrisisCleanup/crisiscleanup-3-api/issues/465

**Comment by aarontitus** [comment]
This is a special case, and as long as we can load the SVI data on a periodic basis (i.e. every two years, with or without a special tool), then these requirements are met. If we can do that, please indicate and close this issue.

**Comment by tabiodun** [comment]
We have a cli tool in the app do do this upload at: `https://github.com/CrisisCleanup/crisiscleanup-3-api/issues/480`

The way we use it is ` python manage.py upload_location_data -f /Users/Tobi/Downloads/SVI2018_US.zip -s 2018.1` locally and once it's in the local db, we can export the insert statements
