### ISSUE TITLE
Make theme variables (RPL_THEME1, RPL_THEME2, RPL_THEME3, RPL_THEME4) accessible for SVI slider integration

### ISSUE THREAD

**Issue by withersjm3** [CrisisCleanup/crisiscleanup-3-web#1111]
Make the four variables accessible to integration within the drop-down menu containing four individual sliders, similarly to how the RPL_THEMES variable is currently used as the main SVI statistic.

In order to do this, it seems that one would need to bring out the four variables from the JSON object, similarly to what has been done for the SVI value currently used in the Crisis Cleanup environment.

**Comment by aarontitus** [comment]
Old.
