### ISSUE TITLE
Deep filter not working

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1119]
If you filter for say 'Muck out" you get say "150 of 500" records.  but now if you go deep and filter for Broken pipe = Yes, (and you know you set that flag On at least 1 case), there is not change in the number.  Furthermore, if you open the filter, your selection for "Broken Pipe" did not save and you have to select it again.

**Comment by aarontitus** [comment]
Fixed.
