### ISSUE TITLE
Agent Cannot change state if Connect fails to authenticate

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#1141]
**Describe the bug**
If Connect Streams fails to authenticate for whatever reason (network error, fluke, connection drop, etc.), and the user was already previously authenticated, the agent is temporarily "frozen" in their current state until a page refresh.

**To Reproduce**
Not exactly simple to reproduce, but possibly forcing a network error could lead to it.

**Expected behavior**
The `StreamsStore` should listen for the events (recently added by aws streams) that indicate websocket/auth failure.
Then, it should appropriately handle either by setting the user to a disconnected state or similar.

**Comment by aarontitus** [comment]
Old
