### ISSUE TITLE
Organization Profile Validates for Non-Numeric Characters

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1155]
**Describe the bug**
/organization/profile phone validates for only non-numeric characters.

**To Reproduce**
1. Go to /organization/profile
2. Edit the phone number. Try to add numbers. You can't do it. Add letters. Letters are fine.

**Expected behavior**
Phone numbers are full of... numbers... and should behave accordingly.

**Screenshots**

**Comment by BradenM** [comment]
Superseded by API#592
