### ISSUE TITLE
Org Details Slide out

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1219]
On the Org details slide out.. make the following modifications:
- [x] Add drop shadow to details slide out
- [x] #1251
![image](https://user-images.githubusercontent.com/699333/130077329-68e4abe7-34e5-452f-b6d6-aead0b3db5da.png)
- [x] details should be:        Incidents  |  Cases  |  Calls  |  Value    and have the donut chart again aggregated for all incidents
![image](https://user-images.githubusercontent.com/699333/130079029-e4cd42cf-3db6-4f32-957a-236561fe0459.png)
- [x] repeat this for individual incident list below.

**Comment by deepanchal** [comment]
Outdated
