### ISSUE TITLE
Bottom 5 Charts: (4) Call Case Volume

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1226]
Case Call Volume
- [ ] this graph should show:  Total calls, Missed Calls and Cases Added.  (not what you see in the picture below.. that is just to give you an idea of style
<img width="665" alt="image" src="https://user-images.githubusercontent.com/699333/130144339-8165c591-8057-4767-b2dd-a104e6d1e994.png">

**Comment by deepanchal** [comment]
Outdated
