### ISSUE TITLE
Make a strong case

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1231]
VERY small enhancement here.  the case number needs to pop on this card...  

Current:  
<img width="193" alt="image" src="https://user-images.githubusercontent.com/699333/130219440-afba4f47-81f3-4621-b3ef-0564ea0ae3af.png">

Proposed:  
- [ ] make extra bold the verb.
- [ ] make extra bold the case #
![image](https://user-images.githubusercontent.com/699333/130220005-4ea5fb4a-fe2b-4867-88cd-c8a262175897.png)

Also this is the setting I used to get it as bold as possible... not sure it it helps...   Figma uses Nunito Sans as the font.. 
![image](https://user-images.githubusercontent.com/699333/130221482-fbb1b0fb-5eb1-48f3-906d-e04c9a817ae4.png)

**Comment by aarontitus** [comment]
I think I have to change this in the localizations, not in code. Non-trivial. Closing for now.
