### ISSUE TITLE
Live Feed Logic Update (see comment)

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1236]
Per Conversation with Aaron. here are our thoughts on what loads in the live stream..   Feel free to poke holes in it or suggest insight we are not thinking of.  

On initial load, grab the last 60 objects and stream them down 1 per second.   
- [x] PLAY this load from oldest to newest in the stream.   so that when you load up the next stream it will continue to "flow" 

Then grab whats new in the stream for the last minute:  

- [x] IF there is more than 60 items, just grab the most recent 60 and stream them out.
- [x] IF there is less than 60 items, space them out within that 60 seconds as appropriate (example, only 30 new events, then load a new one every 2 seconds.      if only 10 new events, then load a new one every 10 seconds).  

This will give us the best feel for both wow factor for the 1st minute, and reality factor that this is really a real time map of what is going on... both in slow times and fast ones.  

- [x] Also, Avoid duplicate event display...  for example. if we showed that RA viewed case Y22, then don't  show that very same event again.. at least not back to back.   
![image](https://user-images.githubusercontent.com/699333/130251045-892ab6c5-6167-40dc-aa04-9a6083335285.png)

In reality there may be a valid case event going on here.. but to the user... they will just think its broken and double counting...

**Comment by aarontitus** [comment]
Yes. I think this is right.

**Comment by arroyoDev** [comment]
Live feed breaking if no issues present..  
- [ ] on first load grab back from as far as you need and fire those off.  
- [ ] on next load DONT clear those off, just append your next set from the fresh stuff.  if there is none.. sit tight.

**Comment by arroyoDev** [comment]
@tabiodun    forgive me for re-opening this..     the only thing to confirm is that once the initial load of events is done, and you switch to the realtime events (even if there was zero events in the last few minutes) the existing list you just ran in at the beginning should not clear.    it should just always append the new stuff and keep pushing the list down.   From what I could test, at the end the list cleared.   

- [ ] dont clear the list after initial load. 

Also, you probably know.. but when playing on live.. its like EVERYTHING compounded with each event and refreshed like crazy.. so much so, that all the pew's even drew at the same time in slow motion.  This may be related to the spamming of event data to the donut chart or other chart stuff... so crossing my fingers this magically goes away tonight if @BradenM  and @deepanchal  can fix that.
