### ISSUE TITLE
Replace the menu on the side

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1256]
wire up the links on the side to behave better in their circumstances.   (obviously I was cutting and pasting,, so make the colors match to look good, not my copy paste thing... 

-[ ] if not logged in, show log in button on top right.  
- [ ] if logged in... show the authenticated avatar and name like have in live...  
- [ ] the non logged in side buttons load to a new tab please.

![image](https://user-images.githubusercontent.com/699333/130720105-20f047e1-dc9e-4049-b9a9-fcb6ecad3e88.png)

**Comment by arroyoDev** [comment]
1.  Wrong menu showing up when not authenticated
2. After Autenticating, the list looks correct (potentially same list) but none of the links work
3. just call me.. its a mess.

**Comment by BradenM** [comment]
@arroyoDev,

1.) Did we settle on an icon for Survivors?

2.) Is the (current) public "Contact" route intentionally left out? (as in, I should remove it?)
![image](https://user-images.githubusercontent.com/5913808/130729952-f2aa7275-1656-4765-bab2-ce2eb3c0e65d.png)
