### ISSUE TITLE
4 icons:  Web links under org details

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1281]
On org details page:
- [ ] replace the web url with an icon that is linked to the site
- [ ] next to it put the Facebook, Twitter, and donation links
- [ ] use this icon for donations:  https://thenounproject.com/search/?q=donate&i=1273952
- [ ] There should be 4 icons under the org name all linked instead now.

------------

- [ ] Add the donations link to the org admin page.  this already exist in django admin 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/699333/131071211-67830af5-7f26-4163-addf-4c545fd5b7dd.png">

**Comment by deepanchal** [comment]
Maybe outdated
