### ISSUE TITLE
Manual dial from work page bug

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1299]
Issue:  when you hit the dialer icon from the map page.. it jumps over to the phone page and says calling shortly, even puts you I a "connecting state" after a while.. but never actually calls.  
 - [ ] fix this to work again
 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/699333/131791725-7db04d79-4c4c-4c5e-b4e6-d194d12a0615.png">

**Comment by BradenM** [comment]
closed in https://github.com/CrisisCleanup/crisiscleanup-3-web/commit/e65159a062210c381f7be344dd10f6de7ad52048
