### ISSUE TITLE
Create 200+ Smiley Faces

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#130]
**Problem**
Users do not have a default profile picture, and are not incentivized to create a profile picture. This will be an issue when it comes to badging and other advanced features.

**Solution**
Catch users' attention by assigning them a silly and unique profile picture.
@aarontitus' daughter, Emma, will draw roughly 200 unique smiley faces expressing all kinds of silly or positive emotion. Instead of a blank default user profile image, each user will be randomly assigned one of these custom-drawn smiley faces.

**Comment by aarontitus** [comment]
I have finally scanned all of the smiley faces with my crappy scanner. So, I was wondering if you could take these crappy scans and work some magic with the colors, and slice them up into square images. I'll leave it up to you to do anything to them that you think is good (e.g. a slightly colored background, changing to SVG, etc.). With the exception of page 10, you can see that they are a systematic combination of standard eyes and standard mouths, with random splashes of color.
I added the crappy scans of the smiley faces to Slack #design3.

**Comment by MariiaNetrix** [comment]
[smiley faces.zip](https://github.com/CrisisCleanup/crisiscleanup-3-web/files/4256223/smiley.faces.zip)
