### ISSUE TITLE
Add Filters to "Personal Info" section

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1311]
**Describe the problem**
Add or move the following filters:

**Describe the solution**
- [ ] Remove "Survivors" heading from the General tab
- [ ] Move "Member of My Organization" to the "Personal Info" tab (`worksiteFilters.member_of_my_org`)
- [ ] Add Older than 60 to "Personal Info" tab (`formLabels.older_than_60`)
- [ ] Add Children in Home to "Personal Info" tab (`formLabels.children_in_home`)
- [ ] Add First Responder to "Personal Info" tab (`formLabels.first_responder`)
- [ ] Add Veteran to "Personal Info" tab (`formLabels.veteran`)

**Additional context and instructions**

**Comment by tabiodun** [comment]
@aarontitus The `high_priority` is a flag and lives in the flags section and I think should stay there for architecture reasons

**Comment by aarontitus** [comment]
@tabiodun makes sense. Can we duplicate it in this section as well.

**Comment by tabiodun** [comment]
We can but it will be a bit messy in the code

**Comment by aarontitus** [comment]
@tabiodun OK, we'll skip that for the moment, then. We have enough messiness that comes back to bite us.
