### ISSUE TITLE
Updates to QR code page

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1319]
Folks are really using the QR code but with some frustration.  Here are some things we can do to improve

#1. Fat Fingers.   with a little CSS, the old guys working these crews could actually use this to report back in the field the work is done with their big ole numbs.     here are some suggestions to making this easier to work with. 

Before (current view)
<img width="355" alt="image" src="https://user-images.githubusercontent.com/699333/134759995-70c833e1-040e-47b0-acd7-3316bb0ad9f1.png">

After:  
- [ ] re-arrange header information to fit side by side with phone numbers
- [ ] make the case status icons possibly bigger

<img width="357" alt="image" src="https://user-images.githubusercontent.com/699333/134759945-90f40b66-4e11-47d3-8ffd-ecb394e88577.png">

- [ ] make the case status selectors as big as makes sense.   big enough for the fat fingers to easily choose a status.   
<img width="225" alt="image" src="https://user-images.githubusercontent.com/699333/134759809-10b2c9f4-3033-4b8f-a20b-069c27d792e1.png">

#2. Photos.   Right now, they are asking crews to take pics, email them to the command center where the manually upload them to the case (slow and tedious). We already have a cool photo button,  lets add it to the page with the QR code so they can just scan their paper, hit the photo button, and then take pics with their phone.  I can already do that on my phone from a case.. so doing it from the QR code page seams a bit easier..    

- [ ] add the photos button from the QR code page (see picture above)

**Comment by arroyoDev** [comment]
@tabiodun   Did some testing on staging for what you added.   Pretty cool,   here are a few issues I noticed.  

- [ ] Saved Image Display issues.   When you take a picture they do not show up after you take or upload them.. only the old images (if any were there) show up.   Refreshing the page does not load them either.    in fact,  there several images loaded, but on the QR page it is not refreshing well and when I re-generate the PDF of the case, only the last image shows on the PDF, not the several that are now attached.  

- [ ] When I take a pic with my phone, the thumbail is often sideways, but the image load up correctly... weird... 
- [ ] We should probably use a proper image carrousel or control to display images so they can load up better in full screen mode on a phone.

**Comment by aarontitus** [comment]
Completed.
