### ISSUE TITLE
Survivor Interaction: Color differentiate notes from survivors

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1342]
notes from survivors need to set apart from volunteer notes.  Here is one idea on how to solve the problem:
- [ ] color survivor notes
- [ ] put small key indicating what the color means

![image](https://user-images.githubusercontent.com/699333/150065820-5810cbc8-3ebf-488e-9c87-84b3e59f9533.png)

**Comment by aarontitus** [comment]
Done.
