### ISSUE TITLE
Survivor Interaction: Map interaction on a phone very limited

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1343]
pinch zoom on a map does not work.   therefore you can drag the pin a little at a time, but long jumps will be very hard.   

- [ ] improve map interaction

Also, consider a little padding on the sides so when you are scrolling down the page, you have something to grab on to (cuz if you scroll up on the map as you try to get to the bottom part of the form, you just scroll the map instead.  )

**Comment by aarontitus** [comment]
Completed.
