### ISSUE TITLE
Survivor Interaction:  Deleting images tricky

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1344]
on my phone, everything is pretty small so finding the delete button on a photo thumbnail is hard.. hitting it harder.  often I will accidentally load up the big pic... and when I do that, it would be nice to also have the delete option there.. either way.. an easier way to delete would be good.  plus a "ARE YOU SURE" message would be helpful for for the fat fingered people who want to view the picture, but hit delete instead (which is really easy to do).

**Comment by aarontitus** [comment]
Completed.
