### ISSUE TITLE
Teams:  Change "Cases Assigned" to pull from cases instead of "Work Types"

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1423]
The list view of teams shows how many cases assigned the team has.  but in reality it is actually showing the count of work types.  we dont want that.  

- [ ] change the count of cases assigned on the teams list to reflect the exact same count as is shown on the details view of the team.   

Blocked, need a way to get cases to filter

**Comment by aarontitus** [comment]
Superseded.
