### ISSUE TITLE
Intake Form Formatting Issues

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1454]
@deepanchal , three minor fixes to the intake form UI. See screenshot.
1. The help bubble width should match others, and not span horizontally.
2. Hyperlinks within the help bubble should be underlined. "helpdesk article" is a hyperlink.
3. "Resident Name," "Full Location," and sometimes even "Phone #s" are pre-marked as red.
![image](https://user-images.githubusercontent.com/4184619/184497635-7eaa3299-8146-4e83-a90b-c3e2a2d13c98.png)

**Comment by aarontitus** [comment]
#1 and #2 is fixed. #3 is underway.

**Comment by deepanchal** [comment]
Close per @aarontitus

**Comment by aarontitus** [comment]
The red highlight is not a big deal, and it's kind of growing on me. We might just leave it.
