### ISSUE TITLE
Take it button

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#1563]
Down by the assignment section, we need a small "take it" checkbox that is default on.   What this would do is that ---IF-- i do not choose to assign the case to someone else, then by default the case would be assigned to me when i click on a status button.   

This will eliminate a few pesky extra clicks.

**Comment by DatGamingStache** [comment]
Current Implementation: By default if no agent is assigned to a ticket and you reply to the ticket it will by default assign you to the ticket on reply.
