### ISSUE TITLE
Location Tool: Close Polygon Improvements

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#166]
**Problem**
Closing the multi-vertex polygon tool is hard.

**Solution**
1. Increase the pixel radius that you can click on the first polygon point to close it.
2. When the mouse hovered over the area that will close the polygon, change the background color of the tooltip, "Click first marker to finish" to a light green.
3. Press "Enter" to close the shape.
4. Press "Esc" to cancel all shapes.

**Additional context and instructions**

**Comment by tabiodun** [comment]
1. Is a bit challenging to do, but let me know what you think if the fix I made

2-4 for done

**Comment by aarontitus** [comment]
Love it! The magnet thing is great. Approved.
