### ISSUE TITLE
Location Tool: Action Buttons do Not Work

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#170]
**Bug**
The edit, download, share, and delete buttons do not yet work

**To Reproduce**
1. Go to /locations/new
2. Create a shape and save.
3. Click the edit, download, share, or delete buttons.
4. Error: Nothing happens.

**Expected behavior**
Expected buttons to work.

**Screenshots**
![Buttons Do Not Work](https://user-images.githubusercontent.com/4184619/74347575-86b56e80-4d6e-11ea-999e-fb7b0dce6877.png)

**Desktop (please complete the following information):**
 - Win 10, FF 72

**Comment by tabiodun** [comment]
Edit and share do no yet work/make sense in this context, but the other buttons now work

**Comment by aarontitus** [comment]
This looks good, and the download works. But when I click the trash can, it just spins for several minutes before I give up.

**Comment by tabiodun** [comment]
The issue was that deletion was not working for locations that were attached to another object (like organization or incident). Should be fixed now

**Comment by aarontitus** [comment]
I keep getting a 500 error whenever I click the trash can: "Uh, oh. An unexpected error occurred. That is our fault. Sorry."

**Comment by tabiodun** [comment]
Fixed now
