### ISSUE TITLE
Location Upload: Improvements

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#177]
**Problems**
1. No indication of public/shared/private for uploads.
2. Need brief explanation (e.g. .shp/ .kml, or .zip files)
3. No Manual Location Name option
4. No Cancel Button
5. One-field description not always sufficient (e.g. there are several "Jefferson Counties" or "Congressional District 1s")

**Solutions**
1. Make uploaded locations either public, shared, or private (dropdown or three radio buttons). Default: Shared.
2. Add translated explanation text on the Upload Modal (see screenshot).
3. Type manual title for files with only one shape.
4. Add "Cancel" Button.
5. Add the ability to name locations based upon more than one field, plus other characters. E.g. `{county_name}, {state_name}`.

**Screen Shot**
![Add Explanation Text](https://user-images.githubusercontent.com/4184619/74457539-9c499780-4e45-11ea-82e1-7d60c9263e6e.png)

**Comment by tabiodun** [comment]
Is this the right screenshot?

**Comment by aarontitus** [comment]
Nope. Sorry about that. Fixing...

**Comment by aarontitus** [comment]
It looks like all of the other essential location functionality is working. Once this is complete, I can start making some substantial progress on pre-loading the `locations` table during the migration.

**Comment by aarontitus** [comment]
1. Done. Approved.
2. Done. Approved.
3. Done. Approved.
4. Done. Approved.
5. I can't figure this one out. For example, I wanted to add bunch of counties with the name profile "County Name, State Name." This corresponded to `NAME`, `STATEFP` in the dataset. However, when I typed that string into the custom name template, all of the counties were named literally "NAME, STATEFP".
I had expected to be able to choose from a list of fields, and construct a name

**Comment by aarontitus** [comment]
{NAME}, {STATEFP} works. Closing and approving.
I got a 500 error, but refreshed and tried again and it worked.
