### ISSUE TITLE
Chrome and Safari Hide the header when you click on the map.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#193]
See video below for example.  

Problem, When the Chrome and Safari Browsers are open, when you click on "Cases" in the side bar, then click anywhere on the map, the header containing the disaster name on the left and your name on the right, disappear.  you can only bring them back by clicking on another side navigation item like "Dashboard".  

This does NOT happen in Firefox.

**Comment by BradenM** [comment]
Sounds like a regression of #114,

does that seem to be the case?

**Comment by arroyoDev** [comment]
[browserIssue.m4v.zip](https://github.com/CrisisCleanup/crisiscleanup-3-web/files/4209267/browserIssue.m4v.zip)

**Comment by arroyoDev** [comment]
yep.  sure does.   #114 looks exactly like it.

**Comment by BradenM** [comment]
Hmm. Never did find out exactly what was causing it, somewhere along the line it got fixed unintentionally (until now).

Will look into it.

**Comment by BradenM** [comment]
For the record,

Currently am unable to reproduce on my system with the following:

**System**: `Arch Linux 5.5.4-1-MANJARO`

**Chrome**: `Google Chrome 80.0.3987.106`
**Chromium**: `Chromium 80.0.3987.106 Arch Linux`
**Firefox**: `Mozilla Firefox 73.0`
**Firefox Dev Edition**: `Mozilla Firefox 74.0b3`
