### ISSUE TITLE
Cypress recursion bug causing RangeError

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#194]
**Describe the bug**
An upstream bug in Cypress is causing semi-random build failures. Opening this to further track the issue.

Active Issue: cypress-io/cypress/issues/4373
WIP PR: cypress-io/cypress/pull/5528

Currently re-running the builds 1-2 times (if it fails initially) will eventually make them pass.

See my comment:

> Can confirm. Currently running `cypress 4.0.2` with all related plugins updated and am experiencing seemingly randomly having CI builds fail on to me due to this bug.
> 
>     * See [Run Cypress Git action step](https://github.com/CrisisCleanup/crisiscleanup-3-web/pull/160/checks?check_run_id=448454731).
> 
>     * See [package.json](https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/master/package.json).
> 
>     * See the cut-down (only the meaningful stuff) logs [here](https://github.com/cypress-io/cypress/files/4209324/7_run_cypress_no_webpack.txt)
> 
> 
> Essentially hits [this spec](https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/3e78943555efb771ec67e127e68048abd5d2d8a6/cypress/integration/authenticated_spec.js#L8) first and immediately raises this error:
> 
> ```
> 2020-02-16T03:18:02.8153966Z Authenticated Layout
> 2020-02-16T03:18:03.7048403Z RangeError: Maximum call stack size exceeded
> 2020-02-16T03:18:03.7048803Z     at get (internal/bootstrap/pre_execution.js:286:8)
> 2020-02-16T03:18:03.7049753Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:44:3)
> 2020-02-16T03:18:03.7050336Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
> 2020-02-16T03:18:03.7050899Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
> 
>              <-- hasBinary error continues to repeat for hundreds of lines -->
> 
> 2020-02-16T03:18:04.1677190Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
> 2020-02-16T03:18:04.1677700Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
> 2020-02-16T03:18:04.1678248Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress percy [39m] stopping percy...
> 2020-02-16T03:18:04.1678694Z [�[35mpercy�[39m] waiting for 0 snapshots to complete...
> 2020-02-16T03:18:04.1679070Z [�[35mpercy�[39m] done.
> 2020-02-16T03:18:04.1679768Z [�[35mpercy�[39m] finalized build #17: �[34mhttps://percy.io/Crisis-Cleanup/crisiscleanup-3-web/builds/4175160�[39m
> 2020-02-16T03:18:14.0064823Z Error: The process '/usr/local/bin/npx' failed with exit code 1
> 2020-02-16T03:18:14.0067190Z     at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1.21.0/dist/index.js:894:25)
> 2020-02-16T03:18:14.0074960Z     at Timeout.HandleTimeout (/home/runner/work/_actions/cypress-io/github-action/v1.21.0/dist/index.js:917:15)
> 2020-02-16T03:18:14.0075340Z     at listOnTimeout (internal/timers.js:533:17)
> 2020-02-16T03:18:14.0075586Z     at processTimers (internal/timers.js:475:7)
> 2020-02-16T03:18:14.0076942Z ##[error]The process '/usr/local/bin/npx' failed with exit code 1
> 2020-02-16T03:18:14.0123488Z ##[error]Node run failed with exit code 1
> ```
> 
> The really strange thing is... sometimes it works fine. Passes without a problem and uploads to percy. I'd say it tends to fail more often then do this, but it's still very strange.
> 
> Hope we can figure this one out!

**Comment by BradenM** [comment]
Update, seems the issue has become known to cypress-io/github-action.

Will be trying there suggested temporary workaround...

![screenshot_2020-02-18T03-37-31](https://user-images.githubusercontent.com/5913808/74723457-3754bf80-5200-11ea-9056-1eb06f1ad0a6.png)

**Comment by jennifer-shehane** [comment]
@BradenM I don't think either of the listed issues is related to this recursion error. 

I just ran into this error myself outside of GitHub Issues on a Mac machine and have opened an issue here https://github.com/cypress-io/code-coverage/issues/142

But...I'm also not sure this is your issue because while you're using `@cypress/code-coverage`, you seem to also have `nyc` installed as a dependency. 

Can you try disabling the use of cypress code-coverage? If this solves your issue, can you then open a new issue describing your usage in https://github.com/cypress-io/code-coverage repo?

If disabling the coverage does not solve your issue, can you then open a new issue in the main Cypress project repo: https://github.com/cypress-io/cypress/issues/new

**Comment by BradenM** [comment]
@jennifer-shehane,

Yeah, I kinda had a feeling it may have been a bit of a stretch... but after searching for a while I was overly optimistic, ha-ha.

We actually currently [do have @cypress/code-coverage](https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/271cad5aa97b936630aab6009f9aa3f66df85600/cypress/support/index.js#L18) disabled, as I at one point felt it may have been related and it seemed to have a higher chance of running correctly without it.

As for why we have `nyc` and `@cypress/code-coverage`, I was making an attempt merge coverage from cypress and jest, but put it off for later once these issues began to arise.

While I cannot say for sure, it does seem to passing more often than not now, but I will look into opening a new issue tomorrow.

Thanks!
