### ISSUE TITLE
Caller Identification Card

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#202]
**Describe the problem**
Each user in order to work the call system will need to have their card with some basic information about themselves.  This feature does NOT require the addition "more info" to work, but instead just needs the basics

**Describe the solution**
Create the basic ID badge in the upper left corner of the screen that contains:
- [x] photo
- [x] Name
- [x] number
- [ ] link to Edit:  This link will take you to the existing Profile page: (https://deploy-preview-197--crisiscleanup.netlify.com/profile)
- [x] Button to "Take Calls"
- [x] Button to "Return Calls"

UPDATED
![image](https://user-images.githubusercontent.com/699333/75726743-c35af280-5ca8-11ea-829a-2398d1556bb1.png)

Note "Counties" should actually say "States"

What not to include yet:   
- Help icon
- "More info" link

**Additional context and instructions**

**Comment by arroyoDev** [comment]
@vishk1 this item is not done.  the link to edit is not there and the formatting needs a lot of work.  re-opening the case.

**Comment by arroyoDev** [comment]
this is what it currently looks like. 
![image](https://user-images.githubusercontent.com/699333/77241006-d16ea580-6bba-11ea-9174-ecf942a119ac.png)

**Comment by vishk1** [comment]
**This is the updated card:**
![image](https://user-images.githubusercontent.com/60664816/77616566-f6874f00-6eff-11ea-8480-3218d6bec5ca.png)

**Comment by arroyoDev** [comment]
moved the pencil link to another task.. this is good to go.
