### ISSUE TITLE
Case View "Print" Button Causes Formatting Errors

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#222]
**Describe the bug**

**To Reproduce**
1. Go to Cases, Map view
2. Choose TD Imelda. Click on a case. (e.g. https://app.staging.crisiscleanup.io/incident/157/cases/140165)
3. Under "View [Case Number]", click the print button.
4. Bug: No download. Case information disappears. Legend moves up. See Before Print, After Print.

**Expected behavior**
Expected a PDF file to download

**Screenshots**
Before:
![Before Print](https://user-images.githubusercontent.com/4184619/74787557-b1229280-526c-11ea-81b6-ab4908361b70.png)

After:
![After Print](https://user-images.githubusercontent.com/4184619/74787563-b384ec80-526c-11ea-9b2e-ab9f4fae778d.png)

**Desktop (please complete the following information):**
 - Win 10, FF 72

**Additional context**

**Comment by BradenM** [comment]
@tabiodun @aarontitus ,

Appears to be a recent change in the API that broke this and #223 
The download link returns a 500 server error along with a broken PDF.

See: https://api.staging.crisiscleanup.io/worksites/140165/download

**Comment by aarontitus** [comment]
500 error. Awaiting that to clear up to check.
