### ISSUE TITLE
Table View Print in FF does not work

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#223]
**Describe the bug**
Print does not work in FF

**To Reproduce**
1. Go to Cases, Table View
2. Choose TD Imelda. Click several checkboxes for cases.
3. Under the three dots, click "Print."
4. Bug: Nothing happens.

**Expected behavior**
Expected one or more PDF files to download.

**Screenshots**

**Desktop (please complete the following information):**
 - Win 10, FF 72

**Additional context**

**Comment by aarontitus** [comment]
I am still not seeing any reaction from clicking "Print" under the three dots.

**Comment by tabiodun** [comment]
I think this should be fixed. It may take a bit of time to download a couple, but pdf generation is quite intensive
