### ISSUE TITLE
Implement User Profile

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#232]
**Problem**
Users need to be able to edit their profiles.

**Solution**
Implement the user profile as outlined in the following screenshots and wireframes. Note: MVP for v.3.0 is highlighted in red.
Also, the user must be able to edit or add languages. Users will have a primary and secondary languages. The default primary language = default browser language. If no language is detected, default primary language = `portal_portal_settings.default_language_id`.

**Screenshots**
https://projects.invisionapp.com/share/VPVGR517G29#/screens/325320658_User_Profile
https://projects.invisionapp.com/share/VPVGR517G29#/screens/386172870 (Edit Profile)

3.0 MVP is outlined in red below. Any additional features are frosting on the cake:
![User Profile 3 0 MVP](https://user-images.githubusercontent.com/4184619/74874738-695c4380-531e-11ea-95ac-4f3aa5217307.png)
![Edit User Profile 3 0 MVP](https://user-images.githubusercontent.com/4184619/74874741-6b260700-531e-11ea-8757-e24b8dcf6557.png)

**Comment by tabiodun** [comment]
Do we explicitly need a view vs edit mode?

**Comment by aarontitus** [comment]
@tabiodun Short answer: Yes. The view mode is a high-level summary useful in the field.

**Comment by aarontitus** [comment]
@tabiodun Please ignore my last comment about view vs. edit mode. I didn't check the context, and I thought you were talking about the Worksites module.
No, there is no explicit reason why the User Profile view and edit versions need to be different.
Sorry for the confusion. Next time I'll actually read the Issue, and not just the comment.

**Comment by aarontitus** [comment]
This is complete.
