### ISSUE TITLE
Location Tool: Edit if Location Exists

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#259]
**Problem**
There is no easy way to edit existing locations.

**Describe the solution**
1. Create a locations management tool in the Organization section, where the user can see all locations available to them, and edit them.
2. Automatically edit the existing location if the user chooses a location with the same attributes (e.g. "Primary Response Area" and "Team Rubicon USA").

At least the second requirement is a fairly high priority.

**Additional context and instructions**

**Comment by tabiodun** [comment]
New approach 

![ezgif-6-43498b860f51](https://user-images.githubusercontent.com/1372010/75934794-87ac5e00-5e4b-11ea-9274-2f9ced28aff2.gif)
