### ISSUE TITLE
Design: Default Email and SMS Templates

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#27]
Crisis Cleanup contains many alerts. Design 5 email templates that facilitate these use cases:

  | TEMPLATE | DESCRIPTION
-- | -- | --
1 | Setup Template | Any communication related to the mechanics of the site:  new accounts, new organizations, moving organizations, etc.  This is all primary handled via email.  The illustrations below probably fit this category the best.
2 | Cases Template | Any communication related to active cases or case management, scheduling etc.  Thinking out loud here, possibly could have some familiar look or feel as the case print out format (https://projects.invisionapp.com/d/main#/console/14746784/402738499/preview)
3 | Report Template | All of our reports can have some familiar header/footer content.  See task (https://github.com/CrisisCleanup/crisiscleanup-3-web/issues/154)
4 | Survivor Template | Communication to surivors (at least in this first round) should only be via SMS.   This way we can delay a survivors direct interaction with the website and keep our and their focus on the relief organizations we serve.  Because our SMS communications are super limited in size, there may not be much formatting to do here (but give it a shot)
5 | Other Template | We need a generic email template for any future message that does not fit any of the buckets above.

TEMPLATE | EMAIL | SMS | MESSAGE
-- | -- | -- | --
Cases | x |   | Post-disaster invitations to engage with community
Cases | x | x | Check-in request. Will you be there on [date]?
Cases | x | x | Email to phone volunteers whenever one of their cases has been helped
Cases | x |   | Email report with outstanding invitations
Other | x |   | Any other alerts or notifications
Report | x |   | Daily or weekly reports
Report | x |   | Weekly report including hours, completions, overdue cases, over-all status
Setup | x |   | Invitation to activate account/ Join Crisis Cleanup
Setup | x |   | Notification of organization acceptance/approval
Setup | x |   | Invitation to register organization
Setup | x |   | Confirmation of request to register
Setup | x |   | Notification of acceptance or rejection of request to register
Setup | x |   | Notification of moving to another organization/ accept or reject
Survivor |   | x | SMS to survivor with links to photos of home before/ after, 1 week, 1 month, 3 months, 6 months
Survivor |   | x | Automated SMS  requests to survivors asking if they still need help

Design for the following Formats:
- [ ] Email (any sized screen)
- [ ] SMS
Final Output
- [ ] Wireframe or PSD

GOAL:  Design a look for each of the 5 types.  Each should be common enough to know they come from Crisis Cleanup, but different enough to really fit their category.  The text is not as important right now as is getting the template right.  

- [ ]  Setup Template
- [ ]  Cases Template
- [ ]  Report Template
- [ ]  Survivor Template
- [ ]  Other Template

**Comment by MariiaNetrix** [comment]
![image](https://user-images.githubusercontent.com/59447719/73954430-7df61000-490a-11ea-82b4-6eb1db45dbbc.png)

**Comment by MariiaNetrix** [comment]
![image](https://user-images.githubusercontent.com/59447719/73954480-8f3f1c80-490a-11ea-8bbe-bb8d0548dee1.png)

**Comment by MariiaNetrix** [comment]
**Setup Template**
https://invis.io/STVWHX5MBF9#/404214812_1-_Invitation_To_Activate_Account-_Join_Crisis_Cleanup
https://invis.io/ZAVYQ7QKGWP#/404844287_Other_Template_1
https://invis.io/UYVZDBMCE4P#/404844286_Other_Template_2
https://invis.io/JKVZDBUB7CG#/404844285_Other_Template_3
https://invis.io/SZVWHOOG7Q5#/404214811_3-_Invitation_To_Register_Organization
https://invis.io/F9VZDGNMRVE#/404844284_9-_Notification_Of_Acceptance_Or_Rejection_Of_Request_To_Register

**Report templates**
https://invis.io/S6VWHYHUZA3#/404214810_4-_Daily_Or_Weekly_Reports
https://invis.io/C2VZDCLS5DU#/404844283_11-_Weekly_Report_Including_Hours-_Completions-_Overdue_Cases-_Over-All_Status

**Survivor Template**
https://invis.io/3GVYQ412CAE#/404844282_Suvivor_Template
https://invis.io/VYVZDSFT479#/404844281_Suvivor_Template_Photos

**Comment by aarontitus** [comment]
Looks good.
