### ISSUE TITLE
Add Name to Case View

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#271]
**Describe the problem**
- The survivor's name does not appear on the case view.
- The titles, "Street Address" and "Phone Numbers" are probably not necessary.

**Describe the solution**
- Add person's name to the case View.
- Remove the titles, "Street Address" and "Phone Numbers" to get some more space, unless you disagree.
See Screenshot.

**Screenshot**
![Add Name](https://user-images.githubusercontent.com/4184619/75596596-75e34900-5a4e-11ea-9419-1dc08cf43304.png)

**Comment by BradenM** [comment]
@aarontitus,

How's this?
![image](https://user-images.githubusercontent.com/5913808/75600191-18f98a00-5a72-11ea-88f0-bdad34b3ac6e.png)

**Comment by aarontitus** [comment]
Looks great!

**Comment by arroyoDev** [comment]
cant believe I never noticed it missing.   

On a separate note.  what does this mean? 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/699333/75600603-cb335080-5a76-11ea-910f-b15a07c1b670.png">

**Comment by aarontitus** [comment]
That means I messed up on the translation, but I fixed it in today's version of the database.

**Comment by aarontitus** [comment]
Approved.
