### ISSUE TITLE
Design: Add simple search filter to "My Cases" on Dashboard

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#280]
**Problem**
The "My Cases" component of the Dashboard is hard to navigate when there are a lot of cases.

**Solution**
Add a simple search to the "My Cases" to filter the results, based on case number, name, address, phone number.

**Additional context and instructions**

**Comment by OlhaUzkykova** [comment]
https://zpl.io/259K3Rn
