### ISSUE TITLE
Location Tool: Show Second Dropdown on Edit

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#287]
**Describe the bug**

**To Reproduce**
1. Go to `/locations/new`. Create new primary damaged area for an incident. Save
2. You are automatically forwarded to `locations/[id]/edit`
3. The incident name and type are selected and displayed.
4. Error: However, the second dropdown (e.g. the incident name or organization name) does not appear.

**Expected behavior**
If relevant, the contents of the second dropdown should appear on edit.

**Screenshots**
![Show Incident on Location Edit](https://user-images.githubusercontent.com/4184619/75612971-c6f24c00-5ae5-11ea-844e-961b90ddbebd.png)

**Desktop (please complete the following information):**
 - Win 10, FF 73

**Additional context**

**Comment by tabiodun** [comment]
Lets talk about this monday. There is a reason I have it like this

**Comment by aarontitus** [comment]
@tabiodun Sounds good. Talk tomorrow.

**Comment by tabiodun** [comment]
Implemented new option we discussed
