### ISSUE TITLE
Choose our Report Tool for future use

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#297]
- [ ] Tobi and Braden please recommend the tool / plugin as our weapon of choice for doing cool graphs and Charts.  

Then someone else might go in and start doing stuff like this..  

- [ ] Create a card with a basic combo bar chart that looks something like this (ask @BradenM or @tabiodun  )

![image](https://user-images.githubusercontent.com/699333/75849501-97279a80-5daa-11ea-8737-0adb27e6a281.png)

- [ ] Just the UI with mock data.

**Comment by aarontitus** [comment]
Completed.
