### ISSUE TITLE
Stories from people you helped (UI ONLY)

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#298]
The purpose of this section is to give some motivation back to our phone volunteers.   they will get to see progress updates from those they personally helped. 

- [x] Create a master card that contains a repeatable section with case cards for folks they helped. 
- [x] Inside that card, create a individual case card as listed in the image
![image](https://user-images.githubusercontent.com/699333/75849723-3056b100-5dab-11ea-8237-29c92f5353d6.png)

**Comment by arroyoDev** [comment]
hey @vishk1 make sure when you start working on a case you move it to in-progress.

**Comment by vishk1** [comment]
will do

**Comment by arroyoDev** [comment]
image broken.  also, show the card with 2 stories.

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/77619643-ac559c00-6f06-11ea-9f72-23d07f906def.png)
