### ISSUE TITLE
Location Tool: Circle "Add" Tooltip Disappeared

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#316]
**Bug**
The Circle geofencing tool does not contain an "Add"/ "Subtract" button.

**To Reproduce**
1. Go to /locations/new
2. Zoom all the way out to the entire globe.
3. Zoom into somewhere like the Philippines.
4. Click on the circle tool. Create a circle.
5. Bug: No "Add Subtract" tooltip appears

**Expected behavior**
Expected to see an "Add Subtract" Tooltip

**Screenshots**
![No Circle Add](https://user-images.githubusercontent.com/4184619/76172874-a4080d80-615f-11ea-96bf-987fa07d2066.gif)

**Desktop (please complete the following information):**
 - Win 10 FF 73

**Comment by tabiodun** [comment]
Can you try clearing the cache and reloading? I can't repro here

**Comment by aarontitus** [comment]
Oh, I think I know why. Zoom all the way out, then zoom into somwhere like the Philippines, and try. I'll add that to the reproduce steps above.

**Comment by aarontitus** [comment]
Done.
