### ISSUE TITLE
Location Tool: Confusing Buttons: Apply vs. Upload

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#317]
**Problem**
When uploading new locations, there are two buttons: "Apply" and "Upload." Both are yellow, and it's unclear what to do

**Solution**
It appears that the "Upload" button should be removed, since they both appear only AFTER the SHP files have been uploaded.

**Screenshot**
![Confusing Buttons](https://user-images.githubusercontent.com/4184619/76173400-e5e78280-6164-11ea-9d60-3d6cb9b0eb7e.png)

**Comment by tabiodun** [comment]
The upload doesnt happen till you click upload, all that had happened was that the shapefile was inspected. Once you set up the name and type, then it is uploaded, then apply sets the uses the first one that was uploaded and puts it on the map

**Comment by aarontitus** [comment]
Fixed
