### ISSUE TITLE
Design: Public Intake Form and Splash Pages (coronacommunity.org)

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#360]
**Problem**
We need a seperate website for the public to request help with COVID-19 services, housed on coronacommunity.org. Requests will be filtered into crisiscleanup.org, and people will be called back.

**Solution**
Create a simple, lightweight website design for coronacommunity.org that contains the following elements. Note: The pages are not listed in any particular order:

_Home_
How it Works:
- Simple diagram, perhaps video, describing how the service works, caveats, etc.
   _(how it works in a nutshell:  people at high risk from COVID-19 who need to stay isolated as much as possible, but still need help acquiring food, wellness checks, prescriptions, shopping, oxygen, water, submit a request for logistical help getting these thins without being exposed to others.  Volunteers who want to help serve those people have access to these needs and can claim the need and help service those people)_

Intake Form:
- Export the form from the Crisis Cleanup API for COVID-19. Will include things like:
- Duplicate detection (only if the person has entered an email address that matches an email in the system)
- Personal Information
  - Address, phone number, and email
  - Demographic (Dropdown: Elderly, Immuno-compromised, Healthcare Worker or Dependent, Other (Describe Below)
  - Extenuating circumstances (textarea)
  - I am personally sick (checkbox)
  - I or someone in my home is diagnosed with COVID-19 (checkbox)
- Meals
  - Frequency of need (Recurrence mini-app)
  - Number of Adult Meals (integer)
  - Number of child meals (integer)
  - I am able to pay for meals (checkbox)
- Grocery Pickup 
  - Frequency of need (Recurrence mini-app)
  - Address of store (text)
  - I am able to pay for groceries (checkbox)
- Prescription Pickup
  - Frequency of need (Recurrence mini-app)
  - Address of pharmacy (text)
- Wellness Checkup
  - I need medical check-ups (checkbox)
  - I would like emotional or spiritual check-ups (checkbox)
  - Check-ups may be done virtually (over the phone or online) (checkbox)
- Other
  - Please describe other needs (textarea)
- Agree to Privacy Policy and Terms of Service (Required checkbox)
- Areas to add disclaimer reminders (no guaranties, unskilled volunteers, may not be safe, etc.)

Areas Served:
- A small, zoomable map showing the Furthest Extent area from the Crisis Cleanup API for the COVID-19 incident. This will allow people to see where services are being provided, and not.
- Map information will come from the Crisis Cleanup API.

_About_
- Simple, flexible page where we can post text and videos describing the service

_Flatten the Curve_
- Simple, flexible page where we can post text and videos amplifying simple advice on social distancing, etc.

_Privacy Policy_
- Simple mostly-text page where I can add a privacy policy.

_Terms of Service_
- Simple, mostly-text page where I can add terms of service

_How to Volunteer_
- Simple, flexible page where we can post text and videos describing how to help

_Get an Update_
- After you have entered a request, come here to get an update. You may enter your email address and receive an email update on all of the cases you have entered.

**Additional context and instructions**
- The website should be "Powered by Crisis Cleanup." The Crisis Cleanup Pins logo should appear, but not prominently.
- The website needs to be translated into English and Spanish.
- The intake form should be embedable onto other websites.
![Recur 1](https://user-images.githubusercontent.com/4184619/77095362-64e58200-69d3-11ea-82e9-7623d6b5989d.png)
![Recur 2](https://user-images.githubusercontent.com/4184619/77095364-64e58200-69d3-11ea-94f1-3ec996c5d9c6.png)

**Comment by aarontitus** [comment]
See, e.g. https://www.invisiblehandsdeliver.com/request-a-delivery

**Comment by arroyoDev** [comment]
done and live
