### ISSUE TITLE
Explainer Diagram or Video

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#365]
Simple diagram, perhaps video, describing how the service works, caveats, etc.

(how it works in a nutshell: people at high risk from COVID-19 who need to stay isolated as much as possible, but still need help acquiring food, wellness checks, prescriptions, shopping, oxygen, water, submit a request for logistical help getting these thins without being exposed to others. Volunteers who want to help serve those people have access to these needs and can claim the need and help service those people)

**Comment by arroyoDev** [comment]
Assigned to Miles.  waiting on Draft 1

**Comment by aarontitus** [comment]
The need for this has passed, now that coronacommunity.org is retired.
