### ISSUE TITLE
Training page

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#374]
To turn training page live:
- [ ] @arroyoDev to  replace with our new video when it is ready (this will probably update often)
- [ ] link this page to the home page

----------------
- [x] build a static training page with a link to our new training video
- [x] add our old training video as a place holder
- [x] Only add the training link.  Do NOT add any sib links.. they will come another day
![image](https://user-images.githubusercontent.com/699333/77218820-7b87f800-6afd-11ea-8bb1-79cdbc374d96.png)

this is the look of the page. 
![image](https://user-images.githubusercontent.com/699333/77218792-1cc27e80-6afd-11ea-8a8e-dbca9ef2be44.png)

This is a from invision (remember, just the one Mandatory Crisis Cleanup Training Video is all we want for now.  the rest later

https://projects.invisionapp.com/d/main?origin=v7#/console/14746784/308590704/preview?scrollOffset=1503

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/77268788-05a69c80-6c75-11ea-9ca1-db6349304806.png)

**Comment by aarontitus** [comment]
Done
