### ISSUE TITLE
Wire up about us page on home 

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#375]
- [x] Make the About us page live on the home page.

----------------
- [x] build the static about us page.  as laid out here

https://projects.invisionapp.com/d/main?origin=v7#/console/14746784/308584972/preview?scrollOffset=832

- [x] use this for the video on top:  https://youtu.be/kc_T2giyg9Q?t=15
- [x] go get stats from this page (https://www.crisiscleanup.org/about) and add them as small cards in this section:  
![image](https://user-images.githubusercontent.com/699333/77219095-52b53200-6b00-11ea-96ab-bbb40ef56e17.png). just do it statically,  we will do it via data in the future, but not on this one.

- [x] Skip Testimonials section for now

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/77377975-b890fc00-6d42-11ea-91b1-17ca162addfe.png)
