### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#376]
We have no time for the correct model of a contact page, so for now we will do the following:

-[ ] take the code used in the Help button at the bottom of the current crisis cleanup page and add it to the Contact link as the only way to get in touch with us.  

![image](https://user-images.githubusercontent.com/699333/77219514-898d4700-6b04-11ea-8e25-b97825fa164a.png)

that link goes inside the "contact" link. 

![image](https://user-images.githubusercontent.com/699333/77219537-b93c4f00-6b04-11ea-81d9-a9cddaf4ce56.png)

**Comment by BradenM** [comment]
covered in #425
