### ISSUE TITLE
bottom links

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#377]
Add the bottom links to the following pages

**Comment by arroyoDev** [comment]
We need to add the small nav links at the bottom  of the page:  
![image](https://user-images.githubusercontent.com/699333/77219670-e3dad780-6b05-11ea-8a25-243efb7d17a1.png)


- [ ] add the following links on bottom

- [ ] HIDE the Demo link for now (there is no demo yet)
- [ ]  Contact (link this the same way we linked it in case #376 
- [ ] Terms and Privacy will pint to the same page here
https://projects.invisionapp.com/d/main?origin=v7#/console/14746784/310506527/preview?scrollOffset=752

**Comment by erics2783** [comment]
Addressed in #425
