### ISSUE TITLE
Cosmetic change to Request form to make things  clearer.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#381]
We are going to get a lot of confused people who make it all the way down the request help form to get stumped by the last field.   Instead, let's make it clear right off the back that in order for this to work, you need to put in a valid email address of someone already in the organization.   This shifting of the UI is designed to head that off early.  

Old Screen
![image](https://user-images.githubusercontent.com/699333/77240481-3672cd00-6bb4-11ea-857a-504c658aa5ab.png)

- [x] Proposed New Screen
![image](https://user-images.githubusercontent.com/699333/77240726-11cc2480-6bb7-11ea-9d2e-65e763c43af5.png)

- [x] Quick reminder: Make sure any time you type English words, to add two tildas ~~. That will signal me to translate it.

**Comment by aarontitus** [comment]
Love it.

**Comment by aarontitus** [comment]
While we're at it, can we add a field for "Title," and then a dropdown at the bottom for "Primary Language," where the default is English? That will give us a complete user profile.

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/78212246-c813f180-7474-11ea-9ccf-21a97252012b.png)

**Comment by aarontitus** [comment]
Approved and done.
