### ISSUE TITLE
Leader Board

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#385]
Lets Change the functionality on this just a bit that makes more sense now that we are using it.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/699333/77245238-13afdb00-6beb-11ea-8baa-b9a94ceb6549.png">

Lets make this with 2 tabs:   **Online  |   Leaderboard**

**Online** will correspond directly with the number of phone volunteers online working calls 
<img width="285" alt="image" src="https://user-images.githubusercontent.com/699333/77823327-4e70b200-70c8-11ea-99cb-274c05b0ef80.png">

**Leaderboard** will be the history of all phone volunteers who have handled at least 1 or more calls Stacked in Descending order

To do List

- [ ] Link their image with image
- [ ] Link name with volunteer name  PLUS their ID temporarily to make AWS troubleshooting easier (example:  Ross Arroyo (831))
- [ ] link status 
- [ ] Link Organization
- [ ] Count number of calls and link to Call number
- [ ] Link the phone icon with their phone number
- [ ] Hide Chat for now

- [ ] Split into 2 tabs
- [ ] Limit the Online tab to only Agents Online 
- [ ] Show Top 30 Agents sorted in Descending Order

Finally make the time selector functional
<img width="131" alt="image" src="https://user-images.githubusercontent.com/699333/77823490-84fafc80-70c9-11ea-974a-61a8c49ba9e7.png">

- [ ] Default to "Today" and filter for today
- [ ] Add Filter option for (the name of the current disaster selected in the top left)
- [ ] Add Filter for "All Time"

The back end of this id outline briefly in https://github.com/CrisisCleanup/crisiscleanup-3-api/issues/100

Note, code has already been built in staging where you can link the phone number.  Chat will come later.

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/77389498-61e6ea80-6d61-11ea-89d3-c93d1f270293.png)

**Comment by arroyoDev** [comment]
looks good from screen shot,   will approve when I can actually see it on the page.    is the individual item re-usable so it is easy in code to load up 5 or 20 people on the board with a scroll bar?

**Comment by vishk1** [comment]
> 
> 
> looks good from screen shot, will approve when I can actually see it on the page. is the individual item re-usable so it is easy in code to load up 5 or 20 people on the board with a scroll bar?

Yes, the I made a vue component "LeaderboardProfileCard" which has the layout of the individual profile itself, so it can be easily re-used
