### ISSUE TITLE
COVID 19 form tweaks

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#400]
Just something that slipped through on the COVID response form..  I assume we should not have debris on this form

![image](https://user-images.githubusercontent.com/699333/77384499-850a9d80-6d53-11ea-89ca-220985a95fe7.png)

Also, the number headers for 2-5 are not showing white numbers.  
![image](https://user-images.githubusercontent.com/699333/77388592-91482800-6d5e-11ea-9bee-6fe88e32e165.png)

Also, are we not tracking volunteer hours on this one?   I think we should...   What say yeee?

**Comment by aarontitus** [comment]
I took out Debris. And yeah, we should track volunteer hours on this.

**Comment by arroyoDev** [comment]
all looks good now.
