### ISSUE TITLE
Add Links to Home Page

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#425]
**Bug**
Links from the unauthenticated home page/ log in do not work

**Expected behavior**
Links to the following should be wired up.
- [x] About (/about),  #375 
- [x] Blog (http://blog.crisiscleanup.org),  #373 
- [x ] Map,   DONE
- [x] Training (/training), (HIDE)
- [x] Contact (https://crisiscleanup.zendesk.com/hc/en-us/requests/new),  #376
- [x] Demo,  (HIDE)
- [x] Contact again.  #377 
- [x] Terms (/terms), #377 
- [x] and Privacy Policy (/privacy) #377

There are actually a bunch of cases for this:

**Comment by BradenM** [comment]
@tabiodun, I got this. Been meaning to move nav to a separate component anyways...
