### ISSUE TITLE
Reports Tab

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#434]
- [x] Add a Reports Tab to Navigation bar. 
![image](https://user-images.githubusercontent.com/699333/77713466-749d3180-6fa4-11ea-95d9-bd84ab5752af.png)

- [x] Build this reports page.  Pure UI.  
https://projects.invisionapp.com/d/main#/console/14746784/319809006/preview

 - [x] Text Ross and Aaron when completed.

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/77737064-3b33e880-6fdb-11ea-95de-71d1282a26ef.png)

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/77737315-b9908a80-6fdb-11ea-8d56-2cd0af4e9dde.png)

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/77738230-73d4c180-6fdd-11ea-9ebf-c5d627f81337.png)
![image](https://user-images.githubusercontent.com/60664816/77738242-79caa280-6fdd-11ea-9725-dea755b375bd.png)
The scroll screenshots were super choppy, so here are more clear pictures
