### ISSUE TITLE
Reports Upgrade and Clickability

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#437]
In preparation for reporting done here #446 when you do get to this page we should have 1 actual working report, and all the rest are "extra" one day in the future. 

We need to add a report card where the user can download the CSV here.
- [x] Included. (This section will have only one card: "Download CSV", which will actually work.)

Also, look at the bottom of this task, there is a pop up we need if you click on any other report that the csv downloader.   You may want to help wire that up.   see bottom.  

--------------

Make the following edits to the Reports page you just built in case #436 

- [x] get rid of the “Free and Premium headers and instead use Favorites and Report Library”
Make section headers:

- [x] Favorites.    (this section will have no cards under it)
- [x] Report Library (everything will be under here) no favorites selected (no yellow stars yet)

- [x] Re-word all the card with these improved headers and descriptions.  This is the complete list, remove any extras from the previous version you just built

--------- New Headers and Descriptions -----------

**Estimated Commercial Value of Services**
This report calculates the estimated commercial value of services rendered based on the type of work being performed on each property.  For more details on how theses calculations are performed, click here.  <link to http://blog.crisiscleanup.org/2017/10/how-we-calculate-value-of-services.html>

**Requests by County and Type**
This is a breakdown of requests for help by county affected and then detailed by the type of work requested and its age and status. 

**Completion Rates Summary**
This report breaks down the completion rate numbers by Shortest, Average, and Longest wait times for completion over all, and by county.

**Worksite Completion**
This is a detailed breakdown of services requested and what items remain both open and completed.

**Number of Open, Unassigned worksites claimed for more than 6 days.**
This report helps identify items that have been claimed but may not have had significant help rendered and reported for a period of more than 6 days

**Organization Participation Statistics**
This is a breakdown of the Organizations with access to an incident and the types of participation and activities and services performed as it relates to the properties requesting assistance

**Detailed Work Logs with Volunteer Hour Reports**
This report allows for easy extraction of detailed work logs filtered by a variety of options including state, county, city, geo-fenced boundaries, etc.  

**Teammate Invitation and Activity Report**
This is a quick glance at all those you have invited for your organization and their activity status

**Incident Status Dashboard**
A summary of the overall health of a given incident including: Number of requests for help, breakdown by work-type requested, Completion performance, Organizations  participating, call center volume by day, Activity levels by day, 

**Call Center Flow Report**
This is an overview of the number of calls coming into the call center each day broken down by new or follow up calls, return call rates, and volunteer operator performance.

---------- popup ---------

when you click on any one of the report thumbnails that you built, have it load up to this screen with the following changes:

- [x] Clicking on a mini card built in case #436  will load up this pop up
![image](https://user-images.githubusercontent.com/699333/77739113-fad66980-6fde-11ea-9e7b-f319874c977b.png)

- [x] Change wording from the image to say "Your state does not yet have a subscription to this section.  Click here to request more information on report access" 

- [x] Make that link just be a @mail email link to aaron [ at ] crisiscleanup.org

- [ ] Regardless of whether someone actually sends an email to aaron [ at ] crisiscleanup.org, the system should send an email anyway with the username, email, organization, and phone number of the person who clicked the report.

**Comment by aarontitus** [comment]
Done
