### ISSUE TITLE
Wire up the Reports Tab based on Government Role only

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#446]
- [x] IF you are a government Role then show the reports tab
![image](https://user-images.githubusercontent.com/699333/77713466-749d3180-6fa4-11ea-95d9-bd84ab5752af.png)

(ASK Tobi about Roles)

- [x] Reports Tab should link to the Reports page as built in #434  and #436 

- [ ] Confirm that the behavior is to show a list of Possible Reports, and clicking any card prompts a pop up telling the user to contact Aaron as defined in case #437 

Here's the bottom line: Only and ALL organization_organizations.type_t = government should have access to the Reports tab in the nav bar (as well as admins).
I want to record in the events table AND I want to receive an email Every time someone clicks on the Reports tab, and when they click on a link to view a report. Include the person's name, email, phone number, what they clicked, and their organization each time.
When they click on a specific report, a modal appears that says, "We do not yet have an account set up with your state government. Please have someone from your state government contact help@crisiscleanup.org to set up a paid account, so we can provide this report."

**Comment by erics2783** [comment]
issue #434  has an open MR ( #436 ) so i'm going to work off of that branch

**Comment by erics2783** [comment]
The first to tasks on this were done on the ReportsTab branch (PR #436). That probably needs to get merged before the last step can be done.

**Comment by aarontitus** [comment]
This has not been implemented yet.

**Comment by aarontitus** [comment]
Approved and complete.
