### ISSUE TITLE
Case Form positioning on HiDPI Displays

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#463]
**Describe the bug**
Case Form has a position styling issue on HiRes displays. I'd fix it but its 6am again, so im going to bed.

**To Reproduce**
1. Hi Res display
2. Go to case form
3. Get the gap

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5913808/77847126-4d02c080-7180-11ea-9b18-0502d94e45bf.png)

**Smartphone (please complete the following information):**
 - Browser: Firefox

**Comment by aarontitus** [comment]
Completed.
