### ISSUE TITLE
Build an New Incident Creation admin page

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#510]
The creation of a new incident involves many steps.   The idea here is to consolidate as much of that initial back end process into a master page that can do much of the creation from a UI.  For those items that cannot be done via UI, at least provide a checkbox indicating the required action has been taken care of.  This page would include the following: 

- [ ] Incident ID
- [ ] Incident Name Field
- [ ] Incident Languages served
- [ ] Checkbox and link to AWS Connect to create a new hotline number and associate it with a flow
- [ ] Hotline Number Field
- [ ] List of Voice Prompt defaults that can be edited
- [ ] JSON generator for the flows bases on those prompts to import to AWS
- [ ] Checkboxes for setting up AWS Connect Queues 
- [ ] Checkboxes for setting up AWS Connect Routing Profiles
- [ ] Link to create initial Geofence definition of disaster space
- [ ] Invitation sender where we can choose existing organizations in the affected area we can notify the incident is available.  
- [ ] Incident Form field generator
- [ ] we need to have 3 boxes loaded with the template phone script suggestions for inbound, Callback, and Calldowns.  These scripts are often the same but may differ from incident to incident (like COVID 19).

**Comment by aarontitus** [comment]
Completed.
