### ISSUE TITLE
Automatically Name Locations on /admin/organization/{id}

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#524]
**Problem**
The Admin can add primary and secondary response areas to organizations. However, these are not named, and so cannot be easily searched in the Locations Tool later.

**Solution**
The location tool at /location/new automatically suggests a name like "Team Rubicon Primary Response Area," which is correct just about all the time.
When creating a primary or secondary response location at /admin/organization/{id}, automatically create a name just as like in /location/new. Expose the name for editing.

**Additional context and instructions**

**Comment by tabiodun** [comment]
Please test on staging

**Comment by aarontitus** [comment]
@tabiodun On staging:
1. Registered new organization, Temporary Test
2. Updated Organization, including creating a primary response area.
3. Approved organization
4. Went to /locations/new and searched for "Temporary Test." No entries.
5. Confirmed that the location had been created and named properly, however it isn't showing up in the search.
6. Confirmed that the location primary key was properly associated with `organization_organizations.primary_location_id`

So this works, but I'm still experiencing an issue with search.
