### ISSUE TITLE
Default Scroll on for All Forms

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#525]
**Describe the bug**
Some users have complained about not being able to activate, because the form extends below the end of the page.
Please see comments below for references to additional pages that need similar help.

**To Reproduce**
1. Go to a non-scrolling page like https://www.crisiscleanup.org/login.
2. Zoom in by pressing <ctrl>+ several times.
3. Error: the "Register" button and other components fall off the page.

**Expected behavior**
You should be able to scroll if the page falls off the bottom. Make sure that ALL pages with any sort of content are scrollable.

**Screenshots**
![Too Big](https://user-images.githubusercontent.com/4184619/78467363-37821f00-76c9-11ea-8dd0-755517cd5cea.png)

**Desktop (please complete the following information):**
 - Win 10, FF 73

**Comment by aarontitus** [comment]
Waiting for review by @BradenM and/or @tabiodun

**Comment by aarontitus** [comment]
@tabiodun 
This is related to #558 .
Please also review:
1. No Cancel or Save button appears on the phone intake form (/caller), FF
2. Login form is not scrollable, and therefore the buttons can fall off the screen.
3. Activation may not be scrollable.
4. All flags are not scrollable, and therefore buttons can fall off the screen.

**Comment by BradenM** [comment]
Possibly fixed by:
https://github.com/CrisisCleanup/crisiscleanup-3-web/commit/adfdbabdd1d1beea1315bb8c81a9bfd658bd9587
and
#840
