### ISSUE TITLE
When Rejecting an Organization Allow Admin to Add a Personal Note  (was: Do not Send Organization Rejection Email)

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#528]
**Describe the problem**
When rejecting an organization, an email automatically goes out. However, the vast majority of rejections are due to duplication, so the emails are confusing to the users.

**Describe the solution**
Don't send rejection emails any more when the admin rejects an organization. Or at least allow the admin to choose whether to send an email, and add a personal note, in addition to choosing the reason for rejecting the organization.

**Additional context and instructions**

**Comment by wodow** [comment]
Disabling the email was a one line change, so done that.

Modify this issue to 

> allow the admin to choose whether to send an email, and add a personal note, in addition to choosing the reason for rejecting the organization.

at a lower priority?

**Comment by aarontitus** [comment]
@wodow Yes, that would be great. And it would also be great to allow the admin to add a personal note, like "I'm rejecting this registration, but it's only because you registered the same organization 15 times."
