### ISSUE TITLE
bug:  Flags do not wrap if you have too many.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#529]
If you add several flags to a case, they should wrap so you can see them all.  

Currently they just fall off the edge of the page.  

- [ ] make flags wrap. 

![image](https://user-images.githubusercontent.com/699333/78467617-1115b100-76d4-11ea-99fa-4ce731ff097b.png)

**Comment by aarontitus** [comment]
This has been solved.
