### ISSUE TITLE
Use Browser Datetime Format

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#530]
**Bug**
The Invitation Management section (and perhaps other sections) include dates when a user was invited. These dates are in European format (DD/MM/YYYY), but should be in messed-up US-format (MM/DD/YYY), based on browser settings.

**To Reproduce**
1. Go to My Organization
2. Click on the Invitation Management Tab
3. Scroll down to any of the invitations.
4. See the dates in European format

**Expected behavior**
Expected date format to follow the browser settings, if possible.

**Screenshots**
![US Datetime](https://user-images.githubusercontent.com/4184619/78467828-1243df80-76ce-11ea-863a-a52d39b4668c.png)

**Desktop (please complete the following information):**
 - Win10 FF 73

**Comment by COVID-19-DeliveryTool** [comment]
It appears the date format is hard coded as DD/MM/YYYY in the WorksiteRequest, InvitationRequest, and a couple other models.  Would you prefer I update the format to "MM/DD/YYYY" or a true localized date method, eg, moment(XXXXX).toLocalString() or new Date().toLocaleDateString()?

**Comment by tabiodun** [comment]
I would say use the locale.

**Comment by aarontitus** [comment]
I'm pretty sure this has been solved. Closing.
