### ISSUE TITLE
Add this to the News Tab

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#544]
Turn back on the news tab and put this in there for the news.  

~~For those of you who have ever used our call system in the past (as clunky as it was) You're going to LOVE this new system.  It is easier to ever!  However it is brand new, so if you find bugs, please let us know.
 use this picture for the thumbnail. 
![image](https://user-images.githubusercontent.com/699333/78569248-f2eda500-77e8-11ea-97d2-5a801aea98d8.png)

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/78965948-2750b200-7ac4-11ea-878c-79f127f3968e.png)
