### ISSUE TITLE
Can't see buttons to submit case in chrome at 100% zoom

### ISSUE THREAD

**Issue by COVID-19-DeliveryTool** [CrisisCleanup/crisiscleanup-3-web#558]
When in Chrome (Version 79.0.3945.130 (Official Build) (64-bit)) - can't see add/claim buttons when zoomed at 100%. 

1. dev environment
2. add new case
3. scroll down and try to click "add" or "add/claim"

![image](https://user-images.githubusercontent.com/62301029/78733814-81ab1080-7914-11ea-9ee8-c434081b0f44.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version see above

**Comment by aarontitus** [comment]
This is related to #525.

**Comment by BradenM** [comment]
Possibly fixed by:
https://github.com/CrisisCleanup/crisiscleanup-3-web/commit/adfdbabdd1d1beea1315bb8c81a9bfd658bd9587
and
#840
