### ISSUE TITLE
Schedule text boxes are jumbled up

### ISSUE THREAD

**Issue by COVID-19-DeliveryTool** [CrisisCleanup/crisiscleanup-3-web#559]
When adding/editing a case, the scheduling checkboxes are jumbled up and unusable

1. dev
2. add a case/edit existing case
3. click to schedule a need

**Expected behavior**

 - OS: windows
 - Browser chrome 79.0.3945.130 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/62301029/78733980-0564fd00-7915-11ea-85ad-b092b1596fc0.png)

**Comment by aarontitus** [comment]
Completed.
