### ISSUE TITLE
Clicking on "team management" redirects me to a static screen with nothing to do 

### ISSUE THREAD

**Issue by COVID-19-DeliveryTool** [CrisisCleanup/crisiscleanup-3-web#560]
Clicking on "team management" under "My Organizations" redirects me to a screen at https://app.dev.crisiscleanup.io/organization/team - there is just a background picture on that screen. 

1. dev
2. click on my organization
3. click on team management

![image](https://user-images.githubusercontent.com/62301029/78734202-a18f0400-7915-11ea-9219-5888523273ce.png)

**Comment by aarontitus** [comment]
Completed.
