### ISSUE TITLE
add training pages to main phone page as another way to get to it.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#572]
- [x] Add the Test Text that Vishnu did, 
- [x] add the training to the main phone page so you can look at it whenever you want as well. 
![image](https://user-images.githubusercontent.com/699333/78852331-9ef9e080-79e1-11ea-9f83-602ebffef64e.png)

- [x] plus the video's miles pushed to Training.

video link for Basic Training:  https://youtu.be/ot4LZjtK0xo

video link for Phone Training:

video link for Advanced Training:

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/78965992-451e1700-7ac4-11ea-8d36-709ca7bbb766.png)
