### ISSUE TITLE
SQL Queries for Reporting

### ISSUE THREAD

**Issue by COVID-19-DeliveryTool** [CrisisCleanup/crisiscleanup-3-web#604]
**### Query1 - # of cases by state - all time**
select lst.state_output as "State", count(*) as "Case Count" from worksite_worksites ws
join location_state_translation lst on ws.state = lst.state_variants
group by lst.State_Output
order by lst.state_output

**### Query2 - # of cases by city - all time (other option for cities is to do TRIM(UPPER(ws.city)) , but will still run into issues with misspelling - in current dev for example you introduce 64 additional "cities" because of misspelling)**
select lst.state_output as "State", lct.city_output as "City" , count(*) as "Case Count" from worksite_worksites ws
join location_state_translation lst on ws.state = lst.state_variants
join location_city_translation lct on ws.city = lct.city_variants
group by lst.state_output, lct.city_output
order by lst.state_output, lct.city_output

**Comment by COVID-19-DeliveryTool** [comment]
Template for updating translation tables
[CrisisCleanup_StateTranslations.xlsx](https://github.com/CrisisCleanup/crisiscleanup-3-web/files/4465434/CrisisCleanup_StateTranslations.xlsx)

**Comment by aarontitus** [comment]
Completed or not needed.
