### ISSUE TITLE
Design 404, 500 error pages

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#61]
**Problem**
We do not have a 404 or 500 error page.

**Solution**
Design a 400 and 500 error page. Ideally, something interactive that illustrates the value of volunteerism. E.g. the live, interactive map would be great (once it's implemented). But I also like the feel of #2 here: [https://optinmonster.com/best-404-page-examples/](https://optinmonster.com/best-404-page-examples/)

**Comment by OlhaUzkykova** [comment]
https://invis.io/9NW9J2GCRW7#/407861244_500-2-

**Comment by OlhaUzkykova** [comment]
https://invis.io/DRW9J4IMQFV#/407861243_500-3-

**Comment by OlhaUzkykova** [comment]
https://invis.io/KPW9J2FASE9#/407861245_500-1-
https://invis.io/ECW9J5BNYRG#/407861246_404-5-
https://invis.io/QYW9J60TU32#/407861247_404-3-
https://invis.io/MQW9J6AVUCB#/407861248_404-2-
https://invis.io/7NW9J6DKX9V#/407861249_404-1-
