### ISSUE TITLE
bug:  photo upload issues

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#612]
Photo upload system worked for an agent, however she had a few issues.   

- [ ]   there was an unexpected error..  especially when she tried to upload more than 1 at a time.   although it appeared to happen on a single as well. 

<img width="576" alt="Uh, oh  An unexpected server error occured  That is our fault  Sorry" src="https://user-images.githubusercontent.com/699333/79377630-9b0a1900-7f21-11ea-8dd3-cdb1518d92d1.png">

- [ ].  is there a limit to the number of pictures?  was not clear.

- [ ]   the X to close an image needs to be big an pronounced.  it may get camouflaged in the picture and appear like you can close the window.

**Comment by aarontitus** [comment]
I'm going to go ahead and close this one, because we know that people are uploading photos.
