### ISSUE TITLE
update/refresh the mini card when you change your role.  

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#613]
when you  change your role, the mini card on the left does not reflect the change.  it will when you refresh the page, but for UX, we should refresh the mine card to avoid confusion.  

- [ ] refresh mini card on changes to profile.  

<img width="1544" alt="Filters" src="https://user-images.githubusercontent.com/699333/79377812-e58b9580-7f21-11ea-8033-c43f6a038661.png">

**Comment by aarontitus** [comment]
Completed.
