### ISSUE TITLE
add link to the training materials to the navigation.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#614]
turn on "Education" navigation links to the non-logged in side of CC and to the Logged in side.  This will just load up to the current route of training

- [ ] Add outside Nav link:  
<img width="151" alt="image" src="https://user-images.githubusercontent.com/699333/79381856-369e8800-7f28-11ea-98b9-e5c4c5335ac4.png">

- [ ] Add inside Nav Link:  

![image](https://user-images.githubusercontent.com/699333/79381757-153d9c00-7f28-11ea-9eab-7306394f4519.png)

**Comment by aarontitus** [comment]
Use the "Help" icon for the navigation bar.
