### ISSUE TITLE
make the edit button yellow consistent with other edit buttons like on cases.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#616]
- [x] make the edit button on profile yellow like it is elsewhere.  

![image](https://user-images.githubusercontent.com/699333/79402556-de7c7b80-7f51-11ea-8d26-1bcee995ee75.png)

![image](https://user-images.githubusercontent.com/699333/79402583-edfbc480-7f51-11ea-94b3-f8813a90b964.png)

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/79418326-f2d46e80-7f79-11ea-8304-2dd2ded60a6f.png)

**Comment by aarontitus** [comment]
This is done.
