### ISSUE TITLE
Create Call History page

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#618]
Create the Cal History Table UI 

This will share the same space as the Stories of people I helped.  

- [x] Create this table in a new tab.  

<img width="857" alt="image" src="https://user-images.githubusercontent.com/699333/79403514-bfcbb400-7f54-11ea-99b7-904bbb9bdabd.png">

See the rest of the page in context here:  
https://projects.invisionapp.com/d/main#/console/14746784/413692269/preview

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/79911647-4f0a1900-83e6-11ea-90a9-61de72923bce.png)

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/80003753-13735b80-8487-11ea-8512-ea2fea7d5eb9.png)

**Comment by arroyoDev** [comment]
Why no icons?   see image above

**Comment by vishk1** [comment]
https://github.com/CrisisCleanup/crisiscleanup-3-web/pull/652

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/80189726-c56e6d00-85d8-11ea-9867-63fb044749a1.png)
