### ISSUE TITLE
swap out thumbnails

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#619]
swap out the thumbnails of the training videos

![image](https://user-images.githubusercontent.com/699333/79404003-1980ae00-7f56-11ea-9b09-0d146595929a.png)

![Phone Training](https://user-images.githubusercontent.com/699333/79404055-42a13e80-7f56-11ea-9b1b-6f62259732c7.png)
![Basic Training](https://user-images.githubusercontent.com/699333/79404056-42a13e80-7f56-11ea-82dd-146a541aa70f.png)

**Comment by vishk1** [comment]
![image](https://user-images.githubusercontent.com/60664816/79418271-cc163800-7f79-11ea-99d1-e345dee6252b.png)
