### ISSUE TITLE
Organization Capabilities List is Incomplete

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#624]
**Describe the bug**
On https://www.crisiscleanup.org/admin/organization/{id}, the capabilities section does not include an entry for "capabilities.coordination_of_many_organizations"

**Expected behavior**
I added "capabilities.coordination_of_many_organizations" a while ago, and can't figure out why it is not showing up in the list of capabilities.

**Screenshots**

**Comment by tabiodun** [comment]
Should be there now, was the same issue causing some organizations not to load
