### ISSUE TITLE
Accept Request Invitation Does Not Work

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#625]
**Describe the bug**
A potential user "Requested Access" by correctly entering the email address of an existing user. Users from that organization attempted to approve the request, but the "Accept" button had no effect.
Note: now the invited user was independently invited and is now a user, so an invitation should not be sent at this point.
I am identifying the users only by their ID, because this issue is public.

**To Reproduce**
This bug is regarding user_invitations_requests.id = 14. User_id 12754 from org_id 2383 attempted to accept. Other users from the same organization attempted to accept the invitation request, but nothing happened. I did not identify the browser, but the fact that it happened to multiple people makes me suspicious that it was a browser issue.

**Important**
The work-around is for users to invite the person directly. This means that when you fix the "Approve Request" feature, you will need to check the users table. If a user exists, set the request as approved, but do not send the activation email. Otherwise, we will cause confusion among users.

**Comment by BradenM** [comment]
Closed by CrisisCleanup/crisiscleanup-3-api#4b32d90
