### ISSUE TITLE
Add Hotline to Active Incidents

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#630]
Would be nice to had the Hotline number right in the dropdown box of incidents ONLY if it is active.   And color it red.   

example:   of what it would look like:

![image](https://user-images.githubusercontent.com/699333/79495553-631ad880-7fea-11ea-92fd-0acd84a92246.png)

**Comment by arroyoDev** [comment]
@aarontitus what do you think about eventually adding this?

**Comment by aarontitus** [comment]
It would be useful to have that information readily available somewhere, but I don't know if the dropdown is the right place.
I keep loosing in my persistent requests for a "banner" where we can make announcements per incident and site-wide. We really need that. Right now I have to tell people to go to the blog to download the flyers. We are definitely missing people.

**Comment by arroyoDev** [comment]
separate issues.  Defiantly need the banner stuff.  having multiple places where you can see the live hotline is a net positive I think.   have a place to find the number in the dropdown is only a positive side benefit.  The goal is to emphasis (with font color and the number) that these incidents have a live hotline associated with them.   

Agreed, though, having the other banner plus other places to show the hotline also ideal.

**Comment by aarontitus** [comment]
I'm slightly worried about the length. Some incident names can be fairly long. A phone number on top might be too much.
