### ISSUE TITLE
Page Not loading without help

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#633]
Phone Page not loading when you switch events.  

To re-create: 
go to phone page 
then switch to a different incident
page will sit with spinning circle
click on phone tab and everything loads
<img width="900" alt="image" src="https://user-images.githubusercontent.com/699333/79683688-54ead900-81f1-11ea-9b68-72b45bd30855.png">

**Comment by tabiodun** [comment]
Fixec, please check on staging
