### ISSUE TITLE
Photo Bugs

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#642]
Issue 1.  if you select more than one image in upload, it actually does it, but you only see 1 loaded, until you load another, when the rest magically show up.  so now you delete some because there are duplicates. 

issue2. Print PDF version, the photo is 1.  too small, 2 Rotated -90 degrees, and 3 only shows 1 photo (Uploaded 2).  

Here is an example case to help:  https://crisiscleanup.org/incident/201/cases/145455

**Comment by BradenM** [comment]
Superseded by WEB#1080
