### ISSUE TITLE
Design: Add Scroll Bars to Any Scrollable Component

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#643]
**Describe the problem**
Several users have expressed confusion about which components are scrollable. For example, the intake form is scrollable, but has no scroll bars.

**Describe the solution**
Design elegant scroll bars for scrollable components.

**Additional context and instructions**
![Untitled attachment 01927](https://user-images.githubusercontent.com/4184619/79944303-6833b980-8428-11ea-8d93-4f05dfb5ada3.jpg)

**Comment by MariiaNetrix** [comment]
https://app.zeplin.io/project/5dc0187606469a23537c7d9d/screen/5e1980aefde67fbcd967a42b/
