### ISSUE TITLE
On Print Case, Claim is Optional

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#654]
**Problem**
Automatic claiming up on printing is causing problems and confusion in the field. We would like to understand why they are printing and not claiming.

**Solution**
We still want to encourage people to claim cases if they plan to do something with them, but have the option to NOT claim if they want to.
On print, a popup says, "Please claim this case if you plan to do any part of it. If you do not plan to do the work, please let us know why you are printing the case."
[Checkboxes for each of the available work types, all of which are pre-checked]
"Explain if you are not claiming the case:"
[Required Textarea if user prints without claiming]
Buttons: [Claim and Print] [Print without Claiming] [Cancel]

If user clicks "Print without Claiming," then all checked boxes are ignored, and the user MUST add some text in the "Explain if you are not claiming the case" textarea.

Add `print_tokens.no_claim_reason text` to store user explanations why they did not claim the case upon printing.

**Additional context and instructions**

**Comment by tabiodun** [comment]
@aarontitus Having the work type check boxes creates a bit of a tricky situation that we can deal with later, but for now, we keep the all-or-nothing claim but have the modal with the `no_claim_reason_text`

![Annotation 2020-06-13 162653](https://user-images.githubusercontent.com/1372010/84578384-bc0cb000-ad92-11ea-8a5c-c5f6685b5b27.png)

We can then add the work type check boxes as an improvement

**Comment by aarontitus** [comment]
Ok.
One important detail: Do not show the modal if they have already claimed one or more work types.

**Comment by aarontitus** [comment]
Oh, and I realized that I told you to put the buttons in exactly the wrong order. It should be Cancel, Print without claiming, and then Claim and Print.

**Comment by aarontitus** [comment]
Looks great.
