### ISSUE TITLE
WIP: Make Worksite Volunteer Hours Editable

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#655]
**Problem**
A user accidentally entered the number of volunteers and total number of hours instead of listing the volunteers and each of their hours, so instead of 47 hours it lists 470 hours. There is no edit button.

**Describe the solution**
Add a small pencil edit button to edit the hours.

Temporary workaround: add another entry with a negative number of hours.

**Additional context and instructions**

**Comment by wodow** [comment]
Design question: @aarontitus  do you prefer the fields editable dynamically, by a button, in the display case view (i.e. at `/incident/<x>/cases/<y>/`) or along with the other fields in the edit view (i.e. at `/incident/<x>/cases/<y>/edit`) ?

**Comment by wodow** [comment]
re impl: I'm not sure of the correct approach for updating these in the frontend:

1. Vuex-mutate the current `worksite` and submit all together -- but Vuex mutations appear to be avoided; I can't see many
2. add a specialised "update time" API call
3. augment how the case form update works

can come back to this

**Comment by wodow** [comment]
[notes] backend changes necessary:

1. Prevent partial update of fields other than volunteer count and seconds/hours.
1. Prevent update of records other than user's own (access rights TBC)

**Comment by aarontitus** [comment]
@wodow From a design standpoint, I'd prefer that the hours be editable in-line in any view, i.e. by clicking a small pencil icon. I think the hours module was designed to be self-contained, and not change, whether you are in edit or view mode.
Does that help?

**Comment by wodow** [comment]
@aarontitus Yes, thanks. Can save changed values when the user moves the cursor focus from the become-editable fields (hours or volunteers only).

**Comment by tabiodun** [comment]
![Annotation 2020-06-14 183807](https://user-images.githubusercontent.com/1372010/84605813-46761200-ae6e-11ea-99b3-b1bcda728c80.png)
![Annotation 2020-06-14 183811](https://user-images.githubusercontent.com/1372010/84605814-470ea880-ae6e-11ea-9496-0f2b3700f237.png)

**Comment by aarontitus** [comment]
Looks great.
