### ISSUE TITLE
Flag to Move Incident Does not Work

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#670]
**Bug**
The Flag to move a worksite to a new incident is not working.

**To Reproduce**
Case R2 in the Mid-TN Storm, 3 May 2020 is on the wrong incident. I tried to move flag it and move it to the correct incident, but although the buttons all appear to work, the case does not move. https://www.crisiscleanup.org/incident/202/cases/148004

**Expected behavior**
It should move to the other incident.

**Screenshots**

**Desktop (please complete the following information):**
 - Win 10, FF 73

**Comment by wodow** [comment]
Am I right in thinking that CC _doesn't_ want to record/model worksites moving between incidents like it e.g. mdoels worksite merges?

**Comment by tabiodun** [comment]
@wodow We do want to allow you to do this, and the API is built to handle the case of just changing the incident. But I’m not sure why it’s not working ATM

**Comment by wodow** [comment]
note to self: I suspect this is due to https://github.com/CrisisCleanup/crisiscleanup-3-api/blob/6911723edcedef258a2542b87d18947188af99f0/crisiscleanup/worksites/serializers.py#L954 doing its own thing re new case numbers  ;  to investigate and potentially generalise

**Comment by wodow** [comment]
hi @tabiodun I re-read my comment and see I wasn't clear at all :-/

I meant model/record _the history_, i.e. to a database table.

**Comment by tabiodun** [comment]
You’re right I think. I had made a new way of generating the case numbers. But I think I missed this one.

**Comment by wodow** [comment]
> You’re right I think. I had made a new way of generating the case numbers. But I think I missed this one.

nice -- I will take a look

**Comment by tabiodun** [comment]
Like the create part:

`with transaction.atomic():
            incident = Incident.objects.select_for_update().get(pk=incident.id)
            case_number = incident.current_case_number + 1
            incident.current_case_number += 1
            incident.save()

        validated_data.update(
            {
                "reported_by": organization or current_user.organization,
                "created_by": current_user,
                "blurred_location": Point(x, y),
                "name_metaphone": name_metaphone,
                "address_metaphone": address_metaphone,
                "city_metaphone": city_metaphone,
                "county_metaphone": county_metaphone,
                "case_number": f"{incident.case_label}{case_number}",
            }
        ) `

**Comment by aarontitus** [comment]
@wodow Yes. Moving from one incident to another is actually quite common (or at least has been in the past). For example, right now we have a phone hotline open for four concurrent incidents. It is not unusual for a case to be placed on the wrong map in all of the confusion.
Yes: We definitely want to record the fact that a worksite was associated with Incident X, and then moved to Incident Y in the history.

**Comment by wodow** [comment]
> Yes: We definitely want to record the fact that a worksite was associated with Incident X, and then moved to Incident Y in the history.

@aarontitus but there's no table in the schema for this yet?

**Comment by tabiodun** [comment]
The events log is where you want to add this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wodow** [comment]
> The events log is where you want to add this.

a-ha, ok, will look 👍

**Comment by aarontitus** [comment]
@wodow Yes, there are two places this gets recorded:
1. As Tobi suggests, `event_events_logs`
2. `worksite_worksites_work_types_statuses_phases` (`wwwtsp`). Every time ANY piece of data changes in a row--including the `incident_id`-- the row is invalidated by entering a timestamp on `replaced_at` and creating a new row with a `created_at` value at the same time.

**Comment by wodow** [comment]
I've spent some time understanding what `WorksiteSerializer.update()` is trying to do wrt changing incidents.

Something like the following would fix the case number generation (in-place):

```
--- a/crisiscleanup/worksites/serializers.py
+++ b/crisiscleanup/worksites/serializers.py
@@ -957,24 +958,24 @@ class WorksiteSerializer(

             validated_data.update({"blurred_location": Point(x, y)})

+        import ipdb; ipdb.set_trace()
         if validated_data.get(
             "incident"
         ) is not None and instance.incident != validated_data.get("incident"):
             incident = validated_data.get("incident")
-            next_number = f"{incident.case_label}1"
-            latest = Worksite.objects.filter(
-                incident=incident, case_number__isnull=False
-            ).latest("case_number")
-            if latest is not None:
-                next_number = f'{incident.case_label}{int(re.sub("[^0-9]", "", latest.case_number)) + 1}'
-
-            validated_data.update({"case_number": next_number})
+            case_number = incident.current_case_number + 1
+            incident.current_case_number += 1
+            incident.save()
+            validated_data["case_number"] = f"{incident.case_label}{case_number}"
+            changed_incident = True
+        else:
+            changed_incident = False

         for item in validated_data:
             if Worksite._meta.get_field(item):
                 setattr(instance, item, validated_data[item])

-        if len(form_data) > 0:
+        if len(form_data) > 0 or changed_incident:
             existing_work_types = instance.worksiteworktype_set.values_list(
                 "work_type", flat=True
```

...but then the passage that follows assumes/requires that it is given all the form data, to update `WorksiteData` and `WorksiteWorkType` (as per 2. in https://github.com/CrisisCleanup/crisiscleanup-3-web/issues/670#issuecomment-626779751 ). However, from the "Flag" interface in the front-end it receives just

```{"incident":151,"skip_duplicate_check":true}```

so won't work / will lose/hide data if the above is done. (thus, I think this bug is protecting data at present)

proposed course of action: separate out moving a worksite to a new incident (a significant operation!) into its own method and endpoint, as a sibling of `WorksiteSerializer.update()` and then ban it from that. Can share some code between `update()` and the new method.

**Comment by tabiodun** [comment]
@wodow I think it's not a bad idea to have a separate action for moving workistes and making incident a create_only field. However, the flag interface receiving just `{"incident":151,"skip_duplicate_check":true}` isn't really an issue if we are telling the FE that this is a `PATCH` request, which we are. SO it should affect the data in the Vue ORM

**Comment by tabiodun** [comment]
@wodow I think adding a seperate `move_incident` action to the worksite makes sense. It would mean we make incident 'create-only'

**Comment by wodow** [comment]
I don't think I'm the right person to handle this, having now spent some time on it (inc as above). I don't have a good enough understanding of the system to confidently interpret, refactor, change the fundamental stuff going on in https://github.com/CrisisCleanup/crisiscleanup-3-api/blob/bbfdb7b128b690d6eb57b62a318812c99fd62a91/crisiscleanup/worksites/serializers.py#L978 

incomplete plan: based on the existing linked passage, a "move incident" procedure should

(I) Create new `WorkSite` (`worksite_worksites_data`) records as copies of _all_ existing active ones, with the changed incident incident.

Problems: form structure could/will be different, wrt field keys and worktypes. What to do about this? Also "recurring rules" (I'm not sure what these are) and "if selected then work type" values could also be different.

(II) Do similar with `WorksiteWorkType` (`worksite_worksites_work_types_statuses_phases`), but take "recurring rules" into account. And always set the phase to the first phase of the new incident(?)


For completeness, also need to

1. Update case number as per https://github.com/CrisisCleanup/crisiscleanup-3-web/issues/670#issuecomment-632057164
1. Write to event log
1. Add a test, probably requiring creating a second incident fixture

**Comment by tabiodun** [comment]
Ok I’ll take this over. Thanks am for helping enumerate all this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wodow** [comment]
Thanks, @tabiodun

**Comment by tabiodun** [comment]
@wodow I think I found a simple solution:

```
            if len(form_data) == 0:
                form_data = WorksiteDataSerializer(many=True).validate([
                    {'field_key': entry.field_key.key, 'field_value': entry.field_value} for entry in instance.form_data.all()
                ])
```

So basically if you aren't passing form data (incident-only update) we just populate the form data param with the existing form data, and let the rest of the function play out, which will do all the correct creation of work types and invalidation of old ones. If the incident doesn't change, this code won't run at all, and if the form_data is updated alongside the incident, it's a moot point because the remain code woll properly work

**Comment by wodow** [comment]
I see how that would work if `instance.form_data` has the current data, from the db.

What about the concerns re differences in the form structure between incidents?

**Comment by aarontitus** [comment]
Given that all of the data lives in the `worksite_worksites_data` table, would it even be necessary to determine which fields are relevant? If Form 1 has fields A, B, C, D, and E, and Form 2 has A, D, E, F, G, wouldn't that just mean B and C are ignored when the worksite is moved from Incident 1 to Incident 2?

**Comment by tabiodun** [comment]
@aarontitus Part there's a few other considerations because of the way the logic works, but the answer is basically 'kind of'. But the changes made should cover most

**Comment by aarontitus** [comment]
Completed.
