### ISSUE TITLE
Profile Link Broken

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#672]
**Bug**
The profile link is not working. This is a recurring bug, and a problem because users must activate the Phone Role to answer calls.

**To Reproduce**
1. Log in.
2. Click "Profile" under the dropdown for your name
3. Bug: Nothing happens.
Also, there is extra white space to the left. Formatting seems incorrect.
This is a recurring bug.

**Expected behavior**
Profile should load

**Screenshots**
![Profile Link Broken](https://user-images.githubusercontent.com/4184619/81208607-92d75380-8f8c-11ea-93a8-0abf630e6036.png)

**Desktop (please complete the following information):**
 - Win 10, FF; Chrome

**Comment by BradenM** [comment]
resolved in cd7b9ab 

Will be live in next production release
