### ISSUE TITLE
Map Viewport Does not Correctly Update

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#676]
**Bug**
The viewport is not correctly updated. When clicking around the map, refreshing, or changing incidents, you are zoomed back to a previous viewport.

**To Reproduce**

**Expected behavior**
Every time a user changes viewports (e.g. zoom in, zoom out, pan, taken to a case), the viewport AND incident_id should be saved in `user_users.states`. If the user changes incidents, the viewport should be updated to the last viewport for that incident.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wodow** [comment]
Thinking about what the behaviour should be here.   Proposal:

1. Upon any change to the map _or_ the URL, record the map params _and_ the URL to `user_users.states`, by incident ID.
2. Restore these _only_ when the users changes incident via the incident menu.

This allows users to continue to have multiple tabs open with different views, without interference.

Is that too minimal? Also do something on page refresh?

**Comment by aarontitus** [comment]
@wodow That was the basic idea. Just to reflect what I think you're proposing:
1. I am in Big Hurricane incident.
2. I go to the map view of "Work". The map starts on the entire united states.
3. I zoom into Denver, Colorado. Then I pan north to Longmont, Colorado. Because the URL has not changed, the map params are not updated in `user_users.states`.
4. I click the "Table" view of cases, and then click the "Map" view again. Question: There has been no change in URL. Would the map zoom to the United States or Longmont?
5. I repeat step 3. Then I click "Dashboard," then "My Organization," before clicking "Work" again. This requires a change of URL, which would presumably record the map viewport and `incident_id`.
6. I change incidents to "Small Tornado" and click "Work." The map defaults to the United States.
7. I zoom into Nashville, TN.
8. I switch back to "Big Hurricane" incident and click "Work." It should zoom to Longmont, CO, correct?

In this scenario, the only issue we need to handle is when we switch away from the map without changing URLs, (e.g. when the user clicks the Table vs. Map view). Does that seem right to you?
![Table vs  Map View](https://user-images.githubusercontent.com/4184619/81579500-7b6fe000-9369-11ea-98a9-9ebd0865efd9.png)

**Comment by wodow** [comment]
in discussion, discussed that the application already does the stuff in https://github.com/CrisisCleanup/crisiscleanup-3-web/issues/676#issuecomment-626696669 but likely not on enough client-side events => look into that.

**Comment by wodow** [comment]
prelim investigation: PATCH to `/users` is triggered upon map pan, map zoom, switch between map view and table of work, _but not_ open or close of a case.

However, restoring the users states doesn't work consistently within or between incidents, so will try to fix that behaviour before adding more events.

**Comment by wodow** [comment]
There are at least two parts to this:

1. the local instance of the current `User` isn't updated when the state is updated, only the backend record is. This means the map can be restored from _local_ outdated data. I think this will be fixed by https://github.com/CrisisCleanup/crisiscleanup-3-web/pull/690 (if acceptable).
2. `user_users.states` only accommodates a single incident. will follow up on this...

**Comment by wodow** [comment]
The current single incident setup:

the `user_users.states` JSON column stores records of this shape:

```
{
    "filters": {
        "flags": {
            "data": {},
            "name": "flags"
        },
        "fields": {
            "data": {
                "debris": false
            },
            "name": "fields"
        },
        ...
    },
    "incident": 158,
    "showingMap": true,
    "mapViewPort": {
        "_northEast": {
            "lat": 44.96479793033104,
            "lng": -27.421875000000004
        },
        "_southWest": {
            "lat": 8.581021215641854,
            "lng": -117.77343750000001
        }
    },
    "showingTable": false,
    "appliedFilters": {}
}
```

This means it can only hold work map & filter state for the most recently touched incident, not multiple (unless I am missing something).

Alternatives:

1. Maintain this shape and augment with a history subfield, which would map incident ID to a record of the same shape. Replace the top-level fields from the history subfield when the user switches incident.
2. Replace with a top-level mapping of incident ID to records of the exsting shape, and always address `state` by incident ID. 

Second option is cleaner but (a) invalidates existing data (without JSON migration), (b) likely requires more changes to the code.

**Comment by wodow** [comment]
adding @tabiodun for second opinion

**Comment by tabiodun** [comment]
@wodow The states field is free form JSON, so you can change it as you want. I would say we can add a top level ‘incidents’ key that stores the the per incident settings, and just have a key that says what the current incident is. Which is kind of like of like option 2

**Comment by tabiodun** [comment]
Also that would help with backwards compatibility for now.

**Comment by BradenM** [comment]
My bad, linked the wrong issue. :grimacing:

**Comment by wodow** [comment]
reopening as https://github.com/CrisisCleanup/crisiscleanup-3-web/pull/693 throws an error

**Comment by wodow** [comment]
reopened for review

**Comment by aarontitus** [comment]
Seems to work. Approved. Thank you.
