### ISSUE TITLE
BONUS:  duration

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#683]
a huge extra bonus prize would be to answer any phone managers question of Who's been working.    the stats does a lot of that "Julie has 32 calls", but adding one more piece of information would be ideal.. who has been working lately.    To do this we would add the words (hours, minutes, days ago) to the end of the online/offline status.    so the manager could log in and see ahh.. everyones offline, but Julie has only been office for 6 hours, so she definitely worked the calls yesterday.    

so the request is:   add a timer (days ago) right behind the offline status
![image](https://user-images.githubusercontent.com/699333/81476995-96601a00-91da-11ea-93c0-42165f74501e.png)

similar to how we do this:  
![image](https://user-images.githubusercontent.com/699333/81477005-a24bdc00-91da-11ea-860a-0ce7e88005dc.png)

This will also help us for when the day comes we have time to add the tab to the leaderboard that simply shows the same information but sorted not by high score, but by most recent activity.   (ie.  Julie did 300 calls and is on top, but that was soooo 6 tornados ago and has not been active since.   ).

**Comment by aarontitus** [comment]
Yeah, I agree. We should just make an agent table where one column is "Active At", and is sortable. Another column would be number of calls, and another might be organization. 
I guess we could also make the table filterable if we wanted to go all-out.

**Comment by BradenM** [comment]
@aarontitus Currently the leaderboard contains all that info (besides the active at that this issue discusses) for **all** agents. 

Are you talking about maybe putting something similar w/ extra information for organization admins under User Management, maybe?
