### ISSUE TITLE
Add Admin Icon

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#685]
**Problem**
Admin icon is designed, but not implemented

**Solution**
Implement Admin icon

**Additional context and instructions**
![Add Admin Icon to Nav](https://user-images.githubusercontent.com/4184619/81511725-abbb6e00-92d8-11ea-9ebe-5cdb6d4e3b92.png)

**Comment by wodow** [comment]
Is this dependent on https://github.com/CrisisCleanup/crisiscleanup-3-web/issues/521#issuecomment-625283219 , or is it already available on Zeplin or elsewhere?

**Comment by aarontitus** [comment]
@tabiodun Will you make sure that Admin is on the bottom?

**Comment by wodow** [comment]
Icon available at https://app.zeplin.io/project/5dc0187606469a23537c7d9d/screen/5eba591e10b86275495949b8/

**Comment by wodow** [comment]
added in https://github.com/CrisisCleanup/crisiscleanup-3-web/commit/501f03a8fbcdd24f2186962fd9759d9f6176fffe
