### ISSUE TITLE
Delete/Hide PDA after conversion

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#694]
Once you successfully turn a PDA into a Case, Hide the PDA forever.

**Comment by BradenM** [comment]
@aarontitus We definitely have had this conversation before, but can't remember. 

We don't want to actually delete the worksite entry, correct? Just don't display it as a case (in the context of the phone system) if `pda.worksite` is not null?

**Comment by aarontitus** [comment]
@BradenM, yes, that is correct. Do not delete, but hide from the phone system if worksite_id IS NOT NULL.

**Comment by BradenM** [comment]
_Should_ be fixed, having difficulties testing it at the moment... (unrelated issue, my ISP has been hating me for the past couple of days...)
