### ISSUE TITLE
Invitations Throw Error, then success Toasted Message

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#700]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When inviting teammates from the user dashboard, OR the admin dashboard, there is a toasted message that indicates "There is an error, try again later," followed by a success message.

**Screenshots**

**Desktop (please complete the following information):**
 - Win 10, FF 73; iOS Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aarontitus** [comment]
This error is still occurring on dev.

**Comment by BradenM** [comment]
Managed to accidentally reproduce. This error happens whenever you would write an email address then click 'Invite' before letting it generate a 'tag' for the email. 

Added some handling for that issue, also made it generate tags on spacebar, and added some more detailed error messages. Thing was actually a bit of a pain :disappointed_relieved:
