### ISSUE TITLE
Implement "Other Organizations" Nav Item

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#701]
**Describe the problem**
Relief organizations need to see basic stats and contact information about other relief organizations.
NOTE: For phone volunteers, the phone number of primary contacts of other organizations should be hidden.

**Describe the solution**
Implement "Other Organizations" (https://projects.invisionapp.com/share/JRMDYNG4Q9Z#/screens/327974835), which would include an alpha-sorted list of organizations with access to the current incident. It would have list of all primary contacts and incident contacts *AND THE ORGANIZATION ROLE (e.g. Statistics, Situational Awareness, etc.)* Hovering over or clicking on the role should display an info box/alt text that includes the strings: `accessRules.{role}_description` and `accessRules.{role}_limitations`. E.g.: `accessRules.situational_awareness_description` and `accessRules.situational_awareness_limitations` for Situational Awareness.
Also, these stats:

- Incidents (integer) `SELECT COUNT(DISTINCT(incident_id)) FROM organization_organizations WHERE organization_id = {organization_id} AND incident_id = {incident_id} AND approved_at IS NOT NULL;`
- Created (integer) `SELECT COUNT(DISTINCT(id)) FROM worksite_worksites WHERE reported_by = {organization_id} AND incident_id = {incident_id};`
- Claimed (integer) `SELECT COUNT(DISTINCT(worksite_id)) FROM worksite_worksites_work_types_statuses_phases WHERE work_type_claimed_by = {organization_id} AND incident_id = {incident_id} AND replaced_at IS NOT NULL;`
- Closed (integer) `SELECT COUNT(DISTINCT(worksite_id)) FROM worksite_worksites_work_types_statuses_phases WHERE work_type_claimed_by = {organization_id} AND incident_id = {incident_id} AND replaced_at IS NOT NULL AND status_key LIKE 'closed_%';`
- Overdue (integer) `SELECT COUNT(DISTINCT(worksite_id)) FROM worksite_worksites_work_types_statuses_phases WHERE work_type_claimed_by = {organization_id} AND incident_id = {incident_id} AND replaced_at IS NOT NULL AND status_key LIKE 'open_%' AND created_at < NOW() - INTERVAL '6' day;`
- Last Login (Hours/days/weeks ago) `SELECT current_sign_in_at FROM user_users WHERE organization_id = 89 AND current_sign_in_at IS NOT NULL ORDER BY current_sign_in_at DESC LIMIT 1;`

**Additional context and instructions**
You will probably need to add a down arrow that opens up more information about the organization to display all of the primary contacts. We'll probably add more statistics with time.

Eventually the integers should be hyperlinks to reports. The most important would be a hyperlink to Overdue worksites. What would you think about adding operators to the search field in "Work"? E.g. "org:Midland County Emergency Management" "status:open" "timing:overdue"? Just a thought.

**Comment by aarontitus** [comment]
@tabiodun Just added a requirement to list the role/level of access.

**Comment by tabiodun** [comment]
@aarontitus Looking now.
