### ISSUE TITLE
Request Access is throwing a 500 Error to demo@crisiscleanup.org

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#709]
**Describe the bug**
On dev, if you send an invitation to demo@crisiscleanup.org, you get a 500 error.

**To Reproduce**
1. Go to https://app.dev.crisiscleanup.io/request_access
2. Complete the form, and send the request to demo@crisiscleanup.org.
3. Error: 500 Error

**Expected behavior**
No error should have occurred. Please try to figure out why this is happening so we can prevent it. I suspect it has to do with requesting access, because I used the demo account to practice with "Request Access" and other similar features, which caused strange errors.

Sentry says, "User.MultipleObjectsReturned
get() returned more than one User -- it returned 2!
browser
Firefox 76.0
level
error
transaction
/invitation_requests"

However, I confirmed that only one demo@crisiscleanup.org exists in the dev db.

**Screenshots**
![500 Error Request Access](https://user-images.githubusercontent.com/4184619/83101567-d98e0a00-a06f-11ea-9ca4-72ea9f1da821.png)

**Desktop (please complete the following information):**
 - Win 10, FF 76

**Comment by BradenM** [comment]
Oh, please disregard. This issue is scoped only to demo user and is something I accidentally caused when testing some stuff with the email case sensitivity problem. Will fix

**Comment by aarontitus** [comment]
Please explain briefly.

**Comment by BradenM** [comment]
It's the email case sensitivity issue at it's core here. You mentioned there is only a single demouser in the database, but currently there is actually 2.

* demouser@crisiscleanup.org
* DEMOuser@crisiscleanup.org

I was testing the email issue. So I will delete the extra user, and then once the case sensitivity issue is solved this can't occur again (but keep in mind, this is a separate bug and is not necessarily scoped to just this one issue, it's just a side effect)

**Comment by aarontitus** [comment]
Great! That makes perfect sense. And it explains why there were two users returned, instead of one.
