### ISSUE TITLE
No User Data Listed in Case History

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#710]
**Describe the bug**
Case history is no longer displaying user names and contact information

**To Reproduce**
1. Go to "Work."
2. Click on any case.
3. Click the "History" button for the case.
4. Error: Only dates are included, not the users who performed the action.

**Expected behavior**
Clicking on the History button should display user names and contact information.

**Screenshots**
![No User Data](https://user-images.githubusercontent.com/4184619/83102021-d9dad500-a070-11ea-847b-a2e145e2bbce.png)

**Desktop (please complete the following information):**
 - Win10, FF 76

**Comment by wodow** [comment]
this was a simple one! 

Fixed in `2b7f69b` on master.

**Comment by BradenM** [comment]
> 2b7f69b: event.user does not exist (anymore?)

Ah yeah :grimacing: , that makes sense.

We made some breaking changes to the events schema ~a week ago. See https://github.com/CrisisCleanup/crisiscleanup-3-api/commit/437ba950b9be30aa7de25b80b17ed65121403d4b

and our [slack discussion](https://crisiscleanup.slack.com/archives/CDDQ9US0L/p1589605123134800)

**Comment by wodow** [comment]
makes sense, and thanks for the detail @BradenM 

a related question, then: in the case of updates to a worksite, should the creating user also be recorded as an actor? A future improvement?

**Comment by BradenM** [comment]
Yeah, eventual plan to have everything hooked up with events. 

See https://github.com/CrisisCleanup/crisiscleanup-3-api/issues/244

**Comment by aarontitus** [comment]
Yes, that is correct. We are working on essentially capturing every click and business action in the events log.

**Comment by aarontitus** [comment]
@wodow Would you mind checking out this use case on Dev? (or others like it): https://app.dev.crisiscleanup.io/incident/199/cases/143582/history
It appears that some of the events are associated with users, and some are not.
![Missing User in History](https://user-images.githubusercontent.com/4184619/83275987-2ca9af00-a18d-11ea-9ba6-92a367ee4a6c.png)

**Comment by wodow** [comment]
yep, will take a look tomorrow

**Comment by wodow** [comment]
<img width="358" alt="Screenshot 2020-06-01 at 11 34 19" src="https://user-images.githubusercontent.com/1140873/83401047-e9a14300-a3fb-11ea-8af4-51e869b64416.png">

I get both entries -- see screenshot --  so this may have been a caching issue, or the deploy hadn't happened. Please try again, @aarontitus

**Comment by wodow** [comment]
Meanwhile, visiting https://app.dev.crisiscleanup.io/incident/199/cases/143582/history from a fresh browser env _before_ visiting https://app.dev.crisiscleanup.io/incident/199/cases/143582/history results in an error for me -> a new bug if it can be reproduced.

**Comment by aarontitus** [comment]
This is the error I get when I visit the link directly: Blank screen.
![Visit Link Error](https://user-images.githubusercontent.com/4184619/83419118-cd90a800-a3e1-11ea-9d28-4085d58b78be.png)

And yes, it appears to be some sort of caching issue. I can now see all users. Thanks, and sorry for making you go down a rabbit hole on this one. I'll create a new issue for the direct link problem.

Closing this issue.

**Comment by wodow** [comment]
no problem -- wasn't a rabbit hole this time!
