### ISSUE TITLE
"Change or Move Organizations" in Profile Does not Work

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#716]
**Describe the bug**
The "Change or Move Organizations" button in Profile is inoperable.

**To Reproduce**
1. Go to Profile. Click the button. Nothing happens.

I can't remember if we built this functionality or not. If we have, please activate the button. If not, please hide the button.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tabiodun** [comment]
We haven't implemented it yet. I'll remove the button for now
