### ISSUE TITLE
AWS Phone System Should Not Listen on Public Pages

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#717]
**Describe the bug**
This is a part of a larger

**To Reproduce**
1. Go to any public, unauthenticated page.
2. Open the console. The AWS Connect API is pinging every 5 seconds, even though you're not logged in.

**Expected behavior**
Pinging should NOT occur on the public website.

**Screenshots**
![Phone Pinging](https://user-images.githubusercontent.com/4184619/83104342-c3834800-a075-11ea-8577-a8623070ae6d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradenM** [comment]
Previously (I dont believe) this was possible due to the way the connect streams integration works, but I tried it again and it's working fine now. Pretty sure SAML auth "fixed" it.

**Comment by BradenM** [comment]
> ...even though you're not logged in.

Just for reference, the "pinging" is actually connects way OF logging in (or at least, checking if the current user has a live session to resume).

**Comment by aarontitus** [comment]
Ok, that makes sense, but there is no reason to do it on unauthenticated pages, or with unauthenticated users, right?

**Comment by BradenM** [comment]
@aarontitus Previously I could only seem to get the connect API to work when initializing it from the root domain, so I needed to do it as early as possible. But somewhere along the line since then the issue no longer appears to be the case, and I suspect it has something do with the SAML auth that replaced the original, connect centric auth.

**Comment by BradenM** [comment]
Let me also clarify that's it's not "us" persay that do the pinging. Once the connect API is initalized it automatically begins pinging until a user is authorized.
