### ISSUE TITLE
Invitation Management Bugs, Features, Questions

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#721]
**Describe the bug**
See screenshot.
1. Filters does not seem to do anything. Is this turned on?
2. Question: If the invitation has expired, will status say "Expired?" Also, can we sort by each column?
3. Instead of "Invitation Date," can we change this to "Expiration Date"? Also, can we change this to US-formatted dates (5/27/2020, vs. 27/05/2020)?
4. The download and print buttons do not seem functional, and the alt text simply says "Button."

**Expected behavior**

**Screenshots**
![Invitation Management Questions](https://user-images.githubusercontent.com/4184619/83277069-c45bcd00-a18e-11ea-8761-0f97863a7ca2.png)

**Comment by tabiodun** [comment]
1. Filters aren't enabled, I don't think we have designs for what filters on this page are (please correct if I'm wrong)
2. The status should say expired if it is expired, but I can double check that
3. I can make that change yes
4. In this case, what will be difference between download and print?

**Comment by aarontitus** [comment]
1. I'm not aware of a design for filters, but what if we got rid of the filters buttons, and just implemented the search/sort feature from My Cases, on this table? That should be more than sufficient.
2. Thanks.
3. Thanks.
4. Download would be a CSV download of the tabular data. Let's get rid of Print. For "Delete Expired," should we add `user_invitations.replaced_at`, and a non-null value means it has been deleted? Man, I regret not using `invalidated_at` as a convention, instead of `replaced_at` ;-)
5. The Alt text for all of these buttons still reads "Button." Any way we can fix that?
