### ISSUE TITLE
Direct Link to Case History Yields Error or Blank Screen

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#724]
**Describe the bug**
Visiting a direct link to case history produces a blank screen.

**To Reproduce**
1. Go directly to https://app.dev.crisiscleanup.io/incident/199/cases/143582/history
2. Error. See Screenshot.

**Expected behavior**
Should load case and history

**Screenshots**
![Visit Link Error](https://user-images.githubusercontent.com/4184619/83419616-8f47b880-a3e2-11ea-9f33-0b537a571781.png)

**Desktop (please complete the following information):**
 - Win 10 FF 76

**Additional context**
First identified in #710

**Comment by wodow** [comment]
whereas it does work if visiting https://app.dev.crisiscleanup.io/incident/199/cases/143582 and then navigating to /history via the UI.

so, solution could be as simple as populating the worksite model the same way (via API call) as when visiting the case

**Comment by aarontitus** [comment]
Agreed.
