### ISSUE TITLE
Add "Invite Teammates" Button to "Invitation Management"

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#728]
**Describe the problem**
Inviting Teammates is important. Users often look for the ability to invite new users under the "Invitation Management" tab of "My Organization." 

**Describe the solution**
The button is on the dashboard and "User Management," but should also be placed on the "Invitation Management" tab. See screenshot.

**Additional context and instructions**
![Add Invite Teammates](https://user-images.githubusercontent.com/4184619/84071264-a3635b00-a98a-11ea-8274-f79d612006a2.png)

**Comment by BradenM** [comment]
:+1: I also found myself expecting to find it under invitation management.

**Comment by tabiodun** [comment]
Yeah. It’s a button component. So we can just drop it in.

**Comment by aarontitus** [comment]
Yeah, I think the "easy" tag on this issue is an understatement ;-)

**Comment by aarontitus** [comment]
I see the button! Closed. Thanks.
