### ISSUE TITLE
Remove Alpha Watermark

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#737]
**Describe the problem**
All pages have a water mark, CRISIS CLEANUP (PREVIEW) - V3.0.0-ALPHA85+8ECB003, which is unnecessary now. However, we still want a way to confirm the release version.

**Describe the solution**
1. Remove the watermark completely.
2. Add the release ID (e.g. "8ECB003") in a place that is visible in the comments of the source code (e.g. when you View Source in the browser).

**Additional context and instructions**

**Comment by BradenM** [comment]
How about adding the hidden comment then just hiding the watermark in production?

**Comment by aarontitus** [comment]
If we need a way to confirm the version that is live, then hiding in production won't help. But if we don't need to confirm the live version, then we should get rid of it all together.
