### ISSUE TITLE
Deleting a User Actually Deletes a User

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#745]
**Describe the bug**
I confirmed that Mark Przybylski (mprzybylski@saginaw***.com) was a member of 211 Northeast Michigan (organization_id = 1088). A primary contact for 211 deleted Mark through the User Management section because he was actually part of county emergency management. Mark then registered a new organization without any error. A search of the database confirmed that the email address no longer existed. This is a problem.
However, I also noticed that the 

When you delete a user, it should remove them from the organization and set their role to be an "Orphaned" user. If the delete function is indeed working without any problem, it means that the system is doing a cascade delete, which would also delete all invitations, invitation requests, worksites, etc.

Indeed, I do not see any invitations to this user, even though there should be.
Incidentally, there are 940 worksites data, but refer to a non-existent worksite. 63 of those worksites have been created since we launched 3.0.
```
SELECT COUNT(id)
FROM worksite_worksites AS ww
WHERE ww.id NOT IN(
	SELECT DISTINCT(worksite_id)
	FROM worksite_worksites_data AS wwd
);

SELECT COUNT(id)
FROM worksite_worksites AS ww
WHERE ww.id NOT IN(
	SELECT DISTINCT(worksite_id)
	FROM worksite_worksites_data AS wwd
)
AND ww.created_at > '2020-03-25'
```

Note: When I approved the new organization with the old user that no longer exists, Mark received an email with an activation link, but the activation link was invalid. On further investigation, the token, 5dc289afa4e84445bc55fae98efbac3a, was already marked "activated = true." I changed that to null and had him try again.
This is the original issue where a previous invitation is re-sent to someone, without resetting the active setting to null. Hasn't this already been fixed? Why not implemented?

Oh, actually it looks like the user was never deleted, just not accessible through the admin interface. He was never marked inactive, but his organization_id was marked null. Neither he nor his invitations would show up in the admin view search.

This is a super high priority bug to track down.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradenM** [comment]
Closed by API#368
