### ISSUE TITLE
Work Type Request Dialogue Box

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#80]
**Problem**
Requesting a work type from another organization can be controversial and fraught with misunderstanding. Setting up each party with a very clear understanding and expectations, and encouraging communication is essential.

**Solution**
_Overview_: Whenever a user requests a work type from another organization, they receive instructions and contact information.
_Details_: 
1. When a user clicks "Request" (see screenshot below), open a dialogue box.
2. On the dialogue box (see screenshot and link below), the user should have the ability to request additional work types. Instead of using checkboxes, use the same "Request" button/interface as the intake form.
3. Once a user clicks "Request" on the intake form or dialogue box, the word changes to "Requested," and remains "Requested" until the request is resolved (Approved, Rejected, or Ignored for 36 hours).
4. The dialogue box contains the following additional elements (not shown on the screenshot):
  - _Instructions_: "You are requesting that [Target Organization Name(s)] assign one or more work types to [Your Organization Name] for case [Case Number]. This is an opportunity for you to develop a relationship with [Target Organization Name(s)]. Please be nice, respectful, and assume that the other organization is acting with the best intentions.
"We encourage you to call them directly. A phone conversation can speed up the process and minimize misunderstandings. Each of the people below will receive an email alerting them of the request, and encouraging to contact you with questions.
"They will be able to take one of three actions:
-- Approve your Request
-- Deny your Request
-- Take No Action
"If they _approve_ your request, you will receive another alert, and your organization will immediately be listed as claiming the work type. If they _deny_ your request, you will receive an alert, and the request will be cancelled. If this happens, please be nice, respectful, and assume the best intentions of the other organization. Please also reach out directly to the person who denied the request if you need any clarification.
"If they _take no action_, the request will automatically be approved after 36 hours, and you will receive an alert."
"Add a note explaining why you are requesting to do this case. Please be respectful. Examples might include:
'This person is a member of our faith community.'
'We are working next door, and can help this person immediately.'
'You marked the case "Closed, done by others." We are the organization that did the work.'
  - _Contacts_: The Dialogue box should include the name, email address, organization name, and cell phone number of the Target Organization(s) Incident Primary Contact(s), the individual who actually claimed the case, and any other user from the Target Organization(s) who have edited the case in the past.
  - _Notes_: A `textarea` field where the requesting user adds notes and context.
  - _Action Buttons_: Yellow button, "Request," and a gray button, "Cancel."
5. Once the requesting user confirms the Dialogue box by clicking "Request", record all relevant information in `worksite_worksites_work_type_requests`, including the notes in `requested_reason`.
6. See #81 for additional instructions on the workflow to approve, deny, or ignore the request.
7. Note: This process works whether the user is requesting one or more work type from one or more organizations.

**Additional context and instructions**
![Request Button](https://user-images.githubusercontent.com/4184619/71546168-43837580-2951-11ea-9866-0ead02bf4ea7.jpg)

The following popups give an idea, but are incomplete. Add the elements listed above.
[https://projects.invisionapp.com/share/JRMDYNG4Q9Z#/screens/333553513](https://projects.invisionapp.com/share/JRMDYNG4Q9Z#/screens/333553513)
![Request Popup](https://user-images.githubusercontent.com/4184619/71545901-1b464780-294e-11ea-8846-6f737c1e8465.jpg)

**Comment by aarontitus** [comment]
Re-opening. The process looks good, but the modal needs the following elements (described above):
* Instructions
* Contacts
* Notes
* Cancel Button

**Comment by tabiodun** [comment]
See at http://localhost:8080/incident/157/cases/140859

**Comment by aarontitus** [comment]
Approved.
