### ISSUE TITLE
Clearing Notes Bug

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#812]
Reported by phone volunteer:  

Hurricane Hanna - doing some call backs. The notes section and status bar do not refresh after the call has been made. It's unclear as to whether the information is being recorded. When I click on Call Complete - Next Call, the next number comes up but the previous call's status and notes remain.

**Comment by BradenM** [comment]
Closing cause intake form save issues were fixed and #830 overlaps/covers the rest
