### ISSUE TITLE
"Other Organizations" Stats are Incorrect

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#837]
**Describe the bug**
At least some stats in "Other Organizations" are incorrect.

**To Reproduce**
1. Go to Hurricane Isaias.
2. Click on "Other Organizations."
3. Scroll down to "NC Conference United Methodist Church Disaster Response"
4. Claimed cases are ~6, but clicking on the map demonstrates that they have claimed dozens.

**Expected behavior**
All stats should be accurate. "Claimed Cases" should be equal to the unique worksite_ids for which they have claimed one or more work_types.
Please also double-check other stats.

**Screenshots**
![Bad Stats](https://user-images.githubusercontent.com/4184619/89721944-61619000-d9a0-11ea-84e5-ffc087e162c3.png)

**Comment by tabiodun** [comment]
This is more about organizations not having access not showing up on the list altogether. The numbers themselves should be correct
