### ISSUE TITLE
Redaction Patterns Incorrect for LTR Download/Zip Code

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#839]
**Describe the bug**
Zip code is improperly redacted in LTR downloads.

**To Reproduce**
1. Log in as cedrcexecutivedirector@o[...].com.
2. The organization, 963, Coastal Empire Disaster Recovery Committee (CEDRC) is LTR and should have access to download client data within their response area.
3. Click "Work," and turn on the filter "Within My Organization Response Area."
4. Download the CSV.
5. Bug: The Zip Code column is blank. There should be no redaction on any of that data. 
Rule:
```
SELECT redaction_pattern_keys FROM worksite_redactions_roles
WHERE org_role_id = 7
AND case_relationship = 'noRelationship'
AND inside_geofence = true;
```

**Expected behavior**
Nothing inside the geofence should be redacted.

**Comment by aarontitus** [comment]
Updated: Postal Code is not downloading for anyone.

**Comment by tabiodun** [comment]
@aarontitus Looks like an issue specific to zip code. Investigating

**Comment by aarontitus** [comment]
@tabiodun You're correct. It was the absence of the field in `incident_fields`. Added the field, and it works like a charm. It was, in fact, behaving exactly as designed.
