### ISSUE TITLE
i18n code showing on /organizations/teams Teams Management page

### ISSUE THREAD

**Issue by tsanders** [CrisisCleanup/crisiscleanup-3-web#908]
**Describe the bug**
An i18n code is showing instead of the translated text on the `/organizations/teams` Teams Management page.

**Screenshots**
![Issue](https://user-images.githubusercontent.com/181519/91561728-b0487880-e901-11ea-8e64-b45c19df5c01.png)

**Comment by aarontitus** [comment]
Completed.
