### ISSUE TITLE
Workorder "Claim" / "Done" buttons go out of view as screen width increases

### ISSUE THREAD

**Issue by tsanders** [CrisisCleanup/crisiscleanup-3-web#909]
**Describe the bug**
Workorder "Claim" / "Done" buttons go out of view as screen width increases.

**To Reproduce**
1. Use any incident.
2. Navigate to the map (Work page) and click any worksite.
3. Ensure your browse window is set to full width (Greater than 1280px)
4. The "Claim" and "Done" button text will be out of view and it's not possible to scroll to see them.
5. Increasing and decreasing the browser window will not cause the buttons to fully appear.

**Screenshots**
![Screen Shot 2020-08-28 at 8 26 11 AM](https://user-images.githubusercontent.com/181519/91566383-31efd480-e909-11ea-9324-334ed2a762ad.png)

**Desktop (please complete the following information):**
 - MacOS
 - Chrome

**Comment by BradenM** [comment]
Possible regression of #558
