### ISSUE TITLE
Callback Number Disappears for Many Users

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#929]
**Describe the bug**
Even though there are 20 or 200 calls to return, the phone callback box above the intake form does not appear for some users (e.g. User 22067). This happens for me as well, intermittently. I can't figure out why.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradenM** [comment]
This should be fixed. Closing for review.
