### ISSUE TITLE
Disappearing Icons on Map

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#937]
**Describe the bug**
From Ross: I stumbled on a small “high priority” bug.  if you go to Marco-Laura and zoom in on Hattiesburg Mississippi where i live, you will see high priority case there X5299 (its a test case i made). it is High priority. click the icon on top to make it regular again.  by doing this, the triangle icon dis-appears and nothing takes its place.  go to dashboard and back and the case is invisible.  search for it and you will see the ghost header X5299.  make priority again and all is well.

From Aaron: I have documented that same issue on several other occasions-- icons that just don't appear. But I hadn't been able to reproduce it.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image (9)](https://user-images.githubusercontent.com/4184619/93006506-5ad3b480-f51a-11ea-8b8c-2d3f16ece387.png)

**Additional context**

**Comment by BradenM** [comment]
Possibly related issues:
#926 #823
