### ISSUE TITLE
Activation link gives WSOD on Edge and Chrome

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#942]
**Describe the bug**
Bug: Activation link gives WSOD on some versions of Edge.

**To Reproduce**
See attached screenshot in Chrome 85

**Expected behavior**

**Screenshots**
![WSOD Invitation](https://user-images.githubusercontent.com/4184619/93010226-4c4fc200-f547-11ea-9d0c-a66dc800954a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradenM** [comment]
Needs reproduction after recent fixes w/ 504 timeouts

**Comment by aarontitus** [comment]
Agreed. Marking closed for now.
