### ISSUE TITLE
Change Base Map

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#960]
**Describe the problem**
1. The current map is not high contrast, and difficult to read except at oblique angles on screens
2. It does not have enough street labels, especially at any significant zoom level, making drawing on the map very hard.

**Describe the solution**
Please change the base map to something like this:
https://www.maptiler.com/maps/#bright//vector/9.45/-86.8215/33.4251 (County lines, clear water features and street labels)
https://www.maptiler.com/maps/#streets//vector/9.45/-86.8215/33.4251 (Street labels, clear water features)

**Additional context and instructions**

**Comment by BradenM** [comment]
To add to this,

What do you think about allowing the user to select from a list of different base maps (satellite/terrain/etc) Similar to a lot of navigation apps.

**Comment by arroyoDev** [comment]
Is that an option on Pitney Bose maps we use?

**Comment by aarontitus** [comment]
@BradenM It might be convenient to allow for Satellite, and, in theory, disaster-specific data imagery as well. For example, sometimes we are able to get access to flood maps that show the furthest extent of the flood. But it is not a high priority compared with other issues.
@arroyoDev It turns out that we are not actually using Pitney Bowes. We still pay $1K per month for Google Maps. Groan.
