### ISSUE TITLE
Filter Should De-emphasize, Rather than Hide Icons (On Map View, but not Table View)

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#961]
**Describe the problem**
When you search for, or filter a location, everything filtered out disappears, which makes you lose context on the map.

**Describe the solution**
Instead, turn filtered-out to white icons, with a thin colored outline ON THE MAP ONLY. This will de-emphasize them, while still providing context I'm pretty sure these have been designed. Touch base with Maria on Slack.
When you zoom out, filtered-out dots should also turn white with a thin outline.
Filtering in the Table View should hide any non-matching cases; not de-emphasize them.

**Additional context and instructions**
![White Icons](https://user-images.githubusercontent.com/4184619/93691343-4145e600-faa1-11ea-8864-842778826073.png)

**Comment by tabiodun** [comment]
Just so you know, this will be a fairly large change, because it will change the underlying way the map works and also basically mean that all cases will be shown at all times. So I imagine this might take a bit of time to think through and implement

**Comment by aarontitus** [comment]
Cool. Let's discuss on Monday to make sure we don't do something stupid. :-)

**Comment by aarontitus** [comment]
One thing to also consider is that this is the way the SVI Slider will work. So it may be worth building the SVI slider component as a part of this issue... or at least the viewing portion.
Implementing SVI on intake, or the equation to equally split a non-linear curve into equal parts will be a separate issue.
