### ISSUE TITLE
Cannot Remove Work Types

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#966]
**Describe the bug**
If you add a work type to a case, you cannot later remove it.

From a discussion with a user:
Bug: I have a question.  OK, I got on the phone and did a case to refresh myself with the process.  Case Z125 (Sally). BTW, she is in Alabama but called in on the Derecho line so I moved the case to the Sally incident.  Anyway,  I saved the incident and mold remediation is showing up as a need, which is NOT needed.  I then went in and edited the case twice to uncheck the mold remediation box.  I then re-saved the case.  I even re-loaded the page.  Both times it said the case was saved successfully.  But, mold remediation still shows up.  Why is this?
The tree was always there.  I originally added the tree but didn't check mold.  Then, after saving, and finding on the map, because I was moving to the new incident, I noticed it said mold as well, which was never checked to begin with. (edited) even now when go back into the map and click on that case, it still shows mold and tree both
You can't remove a work type once it's been added. I'll add this to our list of bugs. Hurricane Sally

**To Reproduce**
1. Create a case with Trees. Save.
2. Edit the case. Add Mold remediation, but uncheck all boxes for trees.
3. Bug: Checkboxes do not uncheck, and Trees are not removed, even though Mold Remediation is added.
4. Uncheck all Mold remediation checkboxes.
5. Bug: Checkboxes do not uncheck, and Mold Remediation is not removed.

**Comment by tabiodun** [comment]
@aarontitus We seem to have made the decision a while ago that claimed work types won't be removed even when all the associated data is removed. It seem like that is what is going on here. I fixed it, but a test failed meaning that I had explicitly added this deliberately.

So what do you think we should be doing here?

**Comment by aarontitus** [comment]
You can remove work types as long as you deliberately null-out all child data from the parent work type.
