### ISSUE TITLE
Frontend has a lot of errors and warnings on developer console

### ISSUE THREAD

**Issue by raymondxd** [CrisisCleanup/crisiscleanup-3-web#978]
**Describe the bug**
When we run the app on localhost, we can see it has a lot of errors and warnings on developer console.
Many of them were related to Vue basis.

**To Reproduce**
Just run the app on localhost and go to developer console.

**Expected behavior**
App should not have those errors and warnings

**Additional context**
While investigating some of the errors in developer console, I found that we have very smooth eslint rule-sets.
Eg. Vue proptype check is not added into current eslint rules.

**Comment by raymondxd** [comment]
Based on the discussion with Aaron, here are my thoughts to improve frontend codebase.
- Update eslint rules to have stricter rules for vue concepts
- Update all components to follow the updated eslint rules to remove possible warnings and errors from developer console  ( i think just fixing code according to eslint rule will remove a lot of warnings and errors from developer console )
- We can’t transform current codebase from JS to TS for now. Better to focus on building new features and making the entire platform stable first. After that, once we think it’s time, we can go ahead and update the codebase to use typescript
- It will be good to update Vue version from 2.x to 3.x once we finish the above steps.

**Comment by BradenM** [comment]
Absolutely. Been making (slow) progress towards this. 

A typescript codebase would definitely be an awesome and worthwhile accomplishment in my eyes, but I definitely agree that it should come after cleaning up. 

One problem we have is the inconsistent method of declaring component props.

I introduced VueTypes a while ago, looking for a faster/easier/stricter way to declare props, but we need to decided whether we want to stick with it or do away with it. 

When we decide on one or the other, we need to ensure it's used consistently and update the existing codebase. 


Tagging in @tabiodun

**Comment by BradenM** [comment]
Also as for Vue 3 -- I started utilizing the new composition api along with a few other backports in the hopes of making the transition a smooth process. 

Definitely agree that an upgrade should be our end goal here.

The performance improvements both in rendering and compile times are substantial between Vue 2 and 3 -- and we would most definitely benefit.

**Comment by BradenM** [comment]
See vue-types rule: https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/666e30c5f57b5e3de9bf8a0fe19ab96805bb3bac/.eslintrc.js#L25
