### ISSUE TITLE
Filter Error: Number of Cases does Not Increase After Removing Filters

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#980]
**Describe the bug**
I turned off the "Claimed by my organization" filter, but the number of cases did not increase.

Note: In a bug I could not reproduce, a user just reported that the "Filters" button does not work on the map, while "Layers" does. He was using Chrome 85.0.4183.102 64 bit, Windows 10. He also reported that the "x" next to "New Case" does not work; I confirmed that, but I'm not sure if it's a bug or not.

**To Reproduce**
1. Turn on "Claimed by my organization" filter. 6 cases remain on Sally for Admin
2. Turned off "Claimed by my organization" filter. All cases should return. They don't. Only 6 remain.
3. Refreshed. No change. See screenshot.
4. Logged in using Chrome. Error persists. Perhaps user.states is not being updated correctly?
5. I destroyed my user states:
```
UPDATE user_users
SET states = '{}'
WHERE id = 14;
```
6. Problem is fixed.

**Expected behavior**
All cases should return when filters are off.

**Screenshots**
![Filter Error](https://user-images.githubusercontent.com/4184619/93782382-bde2dc80-fbe7-11ea-9072-9406067b321f.png)

**Desktop (please complete the following information):**
 - FF 80.0.1, Win10

**Additional context**

**Comment by BradenM** [comment]
Also likely fixed in https://github.com/CrisisCleanup/crisiscleanup-3-web/commit/5a9ccdf5da632b61a399c4bf59d4348acde68e0a

See if you are able to reproduce when that commit goes live.

**Comment by aarontitus** [comment]
A related issue: I switched incidents from Delta to Isaias, and the numbers were a bit messed up.
![image](https://user-images.githubusercontent.com/4184619/95679808-7fab5e00-0b92-11eb-9f1b-4b502ab11f0b.png)

**Comment by aarontitus** [comment]
Fixed
