### ISSUE TITLE
Return of the WSOD

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#982]
**Describe the bug**
User ID 21891 had a WSOD and could not log in. I deleted her states, and the WSOD went away. This was her states:

```{"filters": {}, "incident": 208, "incidents": {"208": {"filters": {}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 30.420700230527785, "lng": -87.60961532592775}, "_southWest": {"lat": 30.33510204068193, "lng": -87.78676986694336}}, "showingTable": false, "appliedFilters": {}}, "210": {"filters": {}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 30.208224042915713, "lng": -93.22757184505464}, "_southWest": {"lat": 30.205544430826226, "lng": -93.23310792446138}}, "showingTable": false, "appliedFilters": {}}, "undefined": {"filters": {}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 42.42345651793833, "lng": -68.59863281250001}, "_southWest": {"lat": 24.44714958973082, "lng": -106.47949218750001}}, "showingTable": false, "appliedFilters": {}}}, "showingMap": true, "mapViewPort": {"_northEast": {"lat": 30.208224042915713, "lng": -93.22757184505464}, "_southWest": {"lat": 30.205544430826226, "lng": -93.23310792446138}}, "showingTable": false, "showingLegend": false, "appliedFilters": {}}```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradenM** [comment]
See if you are able to reproduce this when https://github.com/CrisisCleanup/crisiscleanup-3-web/commit/5a9ccdf5da632b61a399c4bf59d4348acde68e0a is pushed into live. 

May have resolved this problem.

**Comment by aarontitus** [comment]
Agreed. Likely fixed. Marking closed.
