### ISSUE TITLE
"Skip Call" Immediately Sends Another Call

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#995]
**Describe the bug**
Reported by Reed. He clicks "Skip Call," and the system immediately sends him another call. He clicks "Skip Call" again, and the system immediately sends him another call. He repeated this four times before the system placed him in an "Offline" state and the calls stopped coming.

**Comment by BradenM** [comment]
Unable to test currently, but this may have been fixed in the latest api release.

**Comment by BradenM** [comment]
Closed by API#399 & #1005
